import { useEffect, useState } from 'react'
import { api, Job, activeJob, Playlist, MissingTrack } from './api'
import General from './General'
import MatchPicker from './MatchPicker'
import HealthCard, { stamp } from './HealthCard'
import JobsPanel, { JobRow, actionName } from './JobsPanel'

type Enqueue=(action:string,payload?:any)=>Promise<Job>
const currentRoute=()=>{const raw=location.hash.slice(1);try{const key=decodeURIComponent(raw);if(key.startsWith('spotify:')||key.startsWith('apple:'))return `playlist/${encodeURIComponent(key)}`}catch{}return raw||'dashboard'}
const link=(key:string)=>`#playlist/${encodeURIComponent(key)}`
function ordered<T>(rows:T[],value:(r:T)=>any,direction:string){return [...rows].sort((a,b)=>{const x=value(a),y=value(b);if(x===null||x===undefined||x==='')return y===null||y===undefined||y===''?0:1;if(y===null||y===undefined||y==='')return -1;const n=typeof x==='number'?x-y:String(x).localeCompare(String(y),undefined,{numeric:true,sensitivity:'base'});return direction==='asc'?n:-n})}
function Direction({value,onChange}:{value:string;onChange:(s:string)=>void}){return <select aria-label="Sort direction" value={value} onChange={e=>onChange(e.target.value)}><option value="asc">Ascending</option><option value="desc">Descending</option></select>}

export default function App(){
  const [route,setRoute]=useState(currentRoute)
  useEffect(()=>{const f=()=>setRoute(currentRoute());window.addEventListener('hashchange',f);return()=>window.removeEventListener('hashchange',f)},[])
  const page=route.startsWith('playlist/')?'playlists':route.startsWith('settings')?'settings':route
  let detail='';try{if(route.startsWith('playlist/'))detail=decodeURIComponent(route.slice(9))}catch{}
  const [playlists,setPlaylists]=useState<Playlist[]>([]),[missing,setMissing]=useState<MissingTrack[]>([]),[jobs,setJobs]=useState<Job[]>([]),[health,setHealth]=useState<any>({})
  const [submitted,setSubmitted]=useState('')
  const [message,setMessage]=useState(''),[globalQuery,setGlobalQuery]=useState(''),[search,setSearch]=useState<any>(null)
  async function refresh(){const [p,m,j,h]=await Promise.all([api.playlists(),api.missing(),api.jobs(),api.health()]);setPlaylists(p);setMissing(m);setJobs(j);setHealth(h)}
  useEffect(()=>{refresh().catch(e=>setMessage(e.message));const timer=setInterval(()=>refresh().catch(()=>{}),2500);return()=>clearInterval(timer)},[])
  useEffect(()=>{let active=true;setSearch(null);if(!globalQuery.trim())return;const timer=setTimeout(()=>api.search(globalQuery.trim()).then(r=>{if(active)setSearch(r)}).catch(e=>{if(active)setMessage(e.message)}),300);return()=>{active=false;clearTimeout(timer)}},[globalQuery])
  const enqueue:Enqueue=async(action,payload={})=>{try{const job=await api.enqueue(action,payload);setSubmitted(job.id);setMessage(`${actionName(action)} job queued. You can keep using Playlist Bridge.`);await refresh();return job}catch(e:any){setMessage(e.message);throw e}}
  useEffect(()=>{const job=jobs.find(j=>j.id===submitted);if(job&&!activeJob(job)){setMessage(`${actionName(job.action)} ${job.status}${job.error?`: ${job.error}`:'.'}`);setSubmitted('')}},[jobs,submitted])
  const active=jobs.filter(activeJob)
  async function favorite(p:Playlist){try{await api.updatePlaylist(p.key,{favorite:!p.favorite});await refresh()}catch(e:any){setMessage(e.message)}}
  return <div className="shell"><aside><div className="brand">Playlist Bridge</div><nav>{['dashboard','playlists','missing'].map(p=><button className={page===p?'active':''} key={p} onClick={()=>{location.hash=p}}>{p[0].toUpperCase()+p.slice(1)}</button>)}</nav><div className="sidebar-bottom"><button className={page==='settings'?'active':''} onClick={()=>{location.hash='settings'}}>Settings</button><div className="sidebar-version">{health.version||'2.0.0-beta.3'}</div></div></aside>
  <main><header><div><h1>{detail?'Playlist details':page[0]?.toUpperCase()+page.slice(1)}</h1><p role="status">{message||'Spotify / Apple Music → Plex'}</p></div><label className="global-search">Search Playlist Bridge<input placeholder="Playlist name, track or artist" aria-label="Search Playlist Bridge" value={globalQuery} onChange={e=>setGlobalQuery(e.target.value)}/></label></header>
    {globalQuery&&<section className="panel"><div className="panel-head"><h2>Search results</h2><button onClick={()=>setGlobalQuery('')}>Close search</button></div><p className="muted">Track search uses saved source lists, health results and mappings. Sync or check health to refresh the index.</p>{search?<><p>{search.playlists.length} playlists · {search.track_count} matching tracks {search.track_count>200?'(first 200 shown)':''}</p>{search.playlists.map((p:any)=><p key={p.key}><a href={link(p.key)} onClick={()=>setGlobalQuery('')}>{p.name}</a></p>)}{search.tracks.map((t:any,i:number)=><p key={i}>{t.title} — {t.artist} · <a href={link(t.playlist_key)} onClick={()=>setGlobalQuery('')}>{t.playlist_name}</a></p>)}</>:<p>Searching…</p>}</section>}
    {!!active.length&&<div className="progress-banner"><span className="spinner"/><span>{active.length} active job(s) · {active.find(j=>j.status!=='queued')?.progress||'Queued'} <a href="#settings/jobs">View jobs / cancel</a></span></div>}
    {page==='dashboard'&&<><section className="cards"><Stat label="Playlists" value={playlists.length}/><Stat label="Favorites" value={playlists.filter(p=>p.favorite).length}/><Stat label="Automatic" value={playlists.filter(p=>p.auto_sync).length}/><Stat label="Missing tracks" value={missing.length}/><Stat label="Health drift" value={playlists.filter(p=>p.health&&!p.health.healthy).length}/><Stat label="Health errors" value={playlists.filter(p=>p.health_attempt?.error).length}/><Stat label="Active jobs" value={active.length}/><Stat label="Never synced" value={playlists.filter(p=>!p.last_synced).length}/></section>{!health.plex_configured&&<p className="health-error">Plex is not configured. <a href="#settings">Open General settings</a></p>}<section className="panel"><h2>Quick actions</h2><Bulk enqueue={enqueue}/><p className="muted">All and Favorites include playlists with automatic runs disabled. Automatics uses only playlists with Auto enabled.</p></section><AddPlaylist jobs={jobs} enqueue={enqueue}/><section className="panel"><h2>Recent activity</h2>{jobs.slice(0,4).map(j=><JobRow key={j.id} job={j} refresh={refresh}/>)}{!jobs.length&&<p>No jobs yet.</p>}</section></>}
    {page==='playlists'&&!detail&&<Playlists playlists={playlists} enqueue={enqueue} refresh={refresh} favorite={favorite}/>}
    {detail&&<Detail key={detail} playlistKey={detail} latest={playlists.find(p=>p.key===detail)} enqueue={enqueue} refresh={refresh} jobs={jobs}/>}
    {page==='missing'&&<Missing tracks={missing} enqueue={enqueue} refresh={refresh}/>}
    {page==='settings'&&<Settings tab={route.split('/')[1]||'general'} jobs={jobs} refresh={refresh} setMessage={setMessage}/>}
  </main></div>
}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><span>{label}</span><strong>{value}</strong></div>}
function Bulk({enqueue}:{enqueue:Enqueue}){const [error,setError]=useState('');async function run(action:string,scope:string){try{await enqueue(action,{scope})}catch(e:any){setError(e.message)}}return <><div className="actions wrap"><button onClick={()=>run('sync','all')}>Sync All</button><button onClick={()=>run('sync','favorites')}>Sync Favorites</button><button onClick={()=>run('sync','automatic')}>Sync Automatics</button><button onClick={()=>run('health','all')}>Check All Health</button></div>{error&&<p className="error">{error}</p>}</>}
function AddPlaylist({jobs,enqueue}:{jobs:Job[];enqueue:Enqueue}){
 const [url,setUrl]=useState(''),[favorite,setFavorite]=useState(false),[auto,setAuto]=useState(true),[id,setId]=useState(''),[analysisId,setAnalysisId]=useState(''),[error,setError]=useState(''),[pending,setPending]=useState(false)
 const job=jobs.find(j=>j.id===id),analysis=jobs.find(j=>j.id===analysisId)
 async function run(action:string){setPending(true);setError('');try{const j=await enqueue(action,{url,favorite,auto_sync:auto});setId(j.id);if(action==='analyze')setAnalysisId(j.id)}catch(e:any){setError(e.message)}finally{setPending(false)}}
 const busy=pending||!!(job&&activeJob(job))
 return <section className="panel"><h2>Add playlist</h2><p className="muted">Analyze checks the source and matching first. Add creates the Plex playlist and registers it. Both run as background jobs.</p><form onSubmit={e=>{e.preventDefault();run('analyze')}}><div className="add"><input required aria-label="New playlist URL" placeholder="Spotify or Apple Music playlist URL" value={url} onChange={e=>{setUrl(e.target.value);setAnalysisId('');setId('')}} disabled={busy}/><button disabled={busy||!url.trim()}>Analyze</button></div><div className="toolbar"><label><input type="checkbox" checked={favorite} onChange={e=>setFavorite(e.target.checked)} disabled={busy}/> Favorite</label><label><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)} disabled={busy}/> Automatic runs</label><button type="button" className="primary" disabled={busy||!url.trim()} onClick={()=>run('add')}>Add Playlist</button></div></form>
 {analysis?.status==='completed'&&analysis.result&&<p>{analysis.result.name} · {analysis.result.source_tracks} source · {analysis.result.matched} matched · {analysis.result.unresolved} unresolved</p>}{error&&<p role="alert" className="error">{error}</p>}{job&&<div role="status"><strong>{actionName(job.action)}: {job.status}</strong><p>{job.progress}</p>{job.error&&<p role="alert" className="error">{job.error}</p>}{job.action==='add'&&job.status==='completed'&&job.result?.key&&<p>Playlist added successfully: <a href={link(job.result.key)}>{job.result.name}</a></p>}<a href="#settings/jobs">View job details / cancel</a></div>}
 </section>
}
function Playlists({playlists,enqueue,refresh,favorite}:{playlists:Playlist[];enqueue:Enqueue;refresh:()=>Promise<void>;favorite:(p:Playlist)=>void}){
 const [query,setQuery]=useState(''),[favorites,setFavorites]=useState(false),[automatic,setAutomatic]=useState(false),[sort,setSort]=useState('name'),[direction,setDirection]=useState('asc'),[error,setError]=useState('')
 const rows=ordered(playlists.filter(p=>(!favorites||p.favorite)&&(!automatic||p.auto_sync)&&p.name.toLowerCase().includes(query.toLowerCase())),p=>(p as any)[sort],direction)
 async function run(fn:()=>Promise<any>){try{await fn();await refresh()}catch(e:any){setError(e.message)}}
 return <section className="panel"><Bulk enqueue={enqueue}/><div className="toolbar"><input aria-label="Filter playlists by name" placeholder="Search playlist name" value={query} onChange={e=>setQuery(e.target.value)}/><label><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)}/> Favorites only</label><label><input type="checkbox" checked={automatic} onChange={e=>setAutomatic(e.target.checked)}/> Automatic only</label><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name</option><option value="last_synced">Last synced</option><option value="added_at">Last added</option></select></label><Direction value={direction} onChange={setDirection}/></div><p>{rows.length} of {playlists.length} playlists · Both filters together show automatic favorites.</p>{error&&<p className="error">{error}</p>}
 {rows.map(p=><article className="playlist-card" key={p.key}><div className="panel-head"><div><button className={`star-button ${p.favorite?'favorite':''}`} aria-label={p.favorite?'Remove favorite':'Add favorite'} onClick={()=>favorite(p)}>{p.favorite?'★':'☆'}</button> <a href={link(p.key)}>{p.name}</a><small> · {p.source}</small></div><span className={`pill ${p.auto_sync?'on':'off'}`}>{p.auto_sync?'AUTO ON':'AUTO OFF'}</span></div><p className="muted">{p.saved_matches} saved matches · {p.unresolved} unresolved · Added: {p.added_at?stamp(p.added_at):'Unknown (older playlist)'}</p><HealthCard playlist={p}/><div className="actions wrap"><button onClick={()=>run(()=>enqueue('sync',{scope:'selected',playlist_keys:[p.key]}))}>Sync Now</button><button onClick={()=>run(()=>enqueue('health',{scope:'selected',playlist_keys:[p.key]}))}>Check Health</button><button onClick={()=>run(()=>api.updatePlaylist(p.key,{auto_sync:!p.auto_sync}))}>{p.auto_sync?'Disable automatic':'Enable automatic'}</button></div></article>)}{!rows.length&&<p>No playlists match these filters.</p>}
 </section>
}
function Missing({tracks,enqueue,refresh}:{tracks:MissingTrack[];enqueue:Enqueue;refresh:()=>Promise<void>}){
 const [query,setQuery]=useState(''),[sort,setSort]=useState('occurrence_count'),[direction,setDirection]=useState('desc'),[selected,setSelected]=useState<MissingTrack|null>(null),[ignore,setIgnore]=useState<MissingTrack|null>(null),[error,setError]=useState('')
 const rows=ordered(tracks.filter(t=>`${t.title} ${t.artist} ${t.album||''}`.toLowerCase().includes(query.toLowerCase())),t=>(t as any)[sort],direction)
 return <section className="panel"><h2>Missing tracks</h2><p className="muted">An occurrence is one appearance of a track. A playlist may contain the same track twice: that is 2 occurrences in 1 playlist. Expand the counts to see where it appears.</p><div className="toolbar"><input aria-label="Search missing tracks" placeholder="Track, artist or album" value={query} onChange={e=>setQuery(e.target.value)}/><label>Sort<select value={sort} onChange={e=>setSort(e.target.value)}><option value="title">Name</option><option value="last_checked">Last checked</option><option value="occurrence_count">Occurrences</option><option value="playlist_count">Playlist count</option></select></label><Direction value={direction} onChange={setDirection}/></div>{error&&<p role="status">{error}</p>}
 {rows.map((t,i)=><article className="playlist-card" key={`${t.title}-${t.artist}`}><div className="panel-head"><div><strong>{t.title}</strong><p>{t.artist} · {t.album||'N/A'}</p></div><div className="actions"><button onClick={()=>setSelected(t)}>Review Match</button><button onClick={()=>setIgnore(t)}>Ignore</button></div></div><small>Last checked by sync/match: {stamp(t.last_checked)}</small><details><summary>{t.occurrence_count} occurrences in {t.playlist_count} playlists</summary>{t.memberships.map(m=><p key={m.key}><a href={link(m.key)}>{m.name}</a> · {m.count} occurrence(s)</p>)}</details></article>)}{!rows.length&&<p>No missing tracks match this view.</p>}
 {selected&&<MatchPicker track={selected} onClose={()=>setSelected(null)} onSave={async(c,keys)=>{await enqueue('fix_match',{title:selected.title,artist:selected.artist,album:selected.album||'',plex_id:c.plex_id,playlist_keys:keys});setError('Match fix queued. Follow progress in Jobs.')}}/>}
 {ignore&&<IgnoreDialog track={ignore} close={()=>setIgnore(null)} done={async()=>{await refresh();setError('Ignore saved. Plex changes apply on the next sync.')}}/>}
 </section>
}
function IgnoreDialog({track,close,done}:{track:MissingTrack;close:()=>void;done:()=>Promise<void>}){
 const [universal,setUniversal]=useState(false),[keys,setKeys]=useState(track.memberships.map(m=>m.key)),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 return <div className="modal-backdrop"><div className="modal" role="dialog" aria-modal="true" aria-label="Ignore track"><h2>Ignore {track.title}</h2><p>{track.artist}</p><label><input type="checkbox" checked={universal} onChange={e=>setUniversal(e.target.checked)}/> Ignore universally — all current and future playlists</label>{!universal&&track.memberships.map(m=><label className="playlist-choice" key={m.key}><input type="checkbox" checked={keys.includes(m.key)} onChange={e=>setKeys(e.target.checked?[...keys,m.key]:keys.filter(k=>k!==m.key))}/>{m.name}</label>)}<p className="muted">Ignored tracks will be skipped by matching and removed from Plex on the next sync. Restore ignored rules in General settings.</p>{error&&<p className="error">{error}</p>}<div className="actions"><button disabled={busy} onClick={close}>Cancel</button><button disabled={busy||(!universal&&!keys.length)} onClick={async()=>{setBusy(true);try{await api.ignore({title:track.title,artist:track.artist,album:track.album||'',universal,playlist_keys:keys});await done();close()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Ignore track</button></div></div></div>
}
function Detail({playlistKey,latest,enqueue,refresh,jobs}:{playlistKey:string;latest?:Playlist;enqueue:Enqueue;refresh:()=>Promise<void>;jobs:Job[]}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(false)
 async function load(){setLoading(true);setError('');try{setData(await api.detail(playlistKey))}catch(e:any){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{load()},[playlistKey])
 const completed=jobs.filter(j=>j.status==='completed').map(j=>j.id).join(',')
 useEffect(()=>{if(data)load()},[completed])
 async function run(action:string){try{await enqueue(action,{scope:'selected',playlist_keys:[playlistKey]})}catch(e:any){setError(e.message)}}
 return <section className="panel"><a href="#playlists">← Back to playlists</a>{error&&<p role="alert" className="error">{error}</p>}{loading&&<p role="status">Loading source tracks and Plex matches…</p>}{data?<><h2>{data.playlist.name}</h2><p>{data.metadata.description}</p><div className="actions"><button onClick={()=>run('sync')}>Sync Now</button><button onClick={()=>run('health')}>Check Health</button><button disabled={loading} onClick={load}>Refresh tracks</button></div><HealthCard playlist={latest||data.playlist}/><input className="track-search" placeholder="Search within this playlist" aria-label="Search within playlist" value={query} onChange={e=>setQuery(e.target.value)}/>{data.tracks.filter((t:any)=>`${t.title} ${t.artist} ${t.album||''} ${t.match?.title||''}`.toLowerCase().includes(query.toLowerCase())).map((t:any)=><div className="missing-row" key={t.index}><div className="grow"><strong>{t.index+1}. {t.title}</strong><small>{t.artist} · {t.album||'N/A'}</small><small>Plex: {t.match?`${t.match.title} — ${t.match.artist}`:'No match'}</small></div><span className="pill">{t.status}</span><button disabled={t.status==='Ignored'} onClick={()=>setSelected(t)}>{t.plex_id?'Fix Match':'Review Match'}</button></div>)}</>:!loading&&<button onClick={load}>Retry loading playlist</button>}{selected&&<MatchPicker track={selected} playlistKey={playlistKey} onClose={()=>setSelected(null)} onSave={async(c,keys)=>{await enqueue('fix_match',{title:selected.title,artist:selected.artist,album:selected.album||'',plex_id:c.plex_id,playlist_keys:keys,replace_playlist_key:playlistKey});await refresh()}}/>}</section>
}
function Settings({tab,jobs,refresh,setMessage}:{tab:string;jobs:Job[];refresh:()=>Promise<void>;setMessage:(s:string)=>void}){return <><div className="settings-tabs">{['general','logs','jobs'].map(t=><a className={tab===t?'active-tab':''} href={`#settings/${t}`} key={t}>{t==='jobs'?'Jobs & schedules':t[0].toUpperCase()+t.slice(1)}</a>)}</div>{tab==='general'&&<><General refresh={refresh} setMessage={setMessage}/><Ignored/></>}{tab==='logs'&&<Logs/>}{tab==='jobs'&&<JobsPanel jobs={jobs} refresh={refresh}/>}</>}
function Ignored(){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');const load=()=>api.ignored().then(setRows);useEffect(()=>{load().catch(e=>setError(e.message))},[]);return <section className="panel"><h2>Ignored tracks</h2><p className="muted">Restoring a rule lets matching consider the track on its next sync.</p>{error&&<p className="error">{error}</p>}{rows.map((r,i)=><p key={i}>{r.title} — {r.artist} · {r.playlist_key==='__global__'?'Universal':r.playlist_key} <button onClick={async()=>{try{await api.restoreIgnore({playlist_key:r.playlist_key,ignore_key:r.ignore_key});await load()}catch(e:any){setError(e.message)}}}>Restore</button></p>)}{!rows.length&&<p>No ignored tracks.</p>}</section>}
function Logs(){
 const [entries,setEntries]=useState<any[]>([]),[level,setLevel]=useState(''),[action,setAction]=useState(''),[error,setError]=useState(''),[clear,setClear]=useState(false),[busy,setBusy]=useState(false)
 async function load(){setBusy(true);try{setEntries((await api.logs(level,action)).entries);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{load()},[level,action])
 return <section className="panel"><div className="panel-head"><h2>Logs</h2><div className="actions"><button disabled={busy} onClick={load}>Refresh logs</button><button onClick={()=>setClear(true)}>Clear logs</button></div></div><p className="muted">Latest 1,000 entries retained; up to 200 shown. Tokens are redacted. Jobs retain their own results when logs are cleared.</p>{clear&&<div className="health-error">Clear all stored application logs? <button onClick={async()=>{try{await api.clearLogs();setClear(false);await load()}catch(e:any){setError(e.message)}}}>Confirm clear</button><button onClick={()=>setClear(false)}>Cancel</button></div>}<div className="toolbar"><label>Level<select value={level} onChange={e=>setLevel(e.target.value)}><option value="">All levels</option><option value="INFO">Information</option><option value="ERROR">Errors</option></select></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="">All actions</option>{['sync','health','analyze','add','fix_match','ignore','startup','jobs'].map(a=><option key={a} value={a}>{actionName(a)}</option>)}</select></label></div>{error&&<p className="error">{error}</p>}<div className="log-view">{entries.map(row=><article className="log-entry" key={row.id}><small>{stamp(row.created_at)} · {row.level} · {actionName(row.operation)}</small><pre>{row.message}</pre></article>)}</div>{!entries.length&&<p>No matching logs.</p>}</section>
}
