import {useEffect,useState} from 'react'
import {api,Job} from './api'
import ErrorNotice from './ErrorNotice'
export default function AvailabilitySettings({jobs}:{jobs:Job[]}){
 const [data,setData]=useState<any>(null),[task,setTask]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 const revision=jobs.filter(j=>j.action==='availability').map(j=>`${j.id}:${j.status}`).join('|')
 const active=jobs.some(j=>j.action==='availability'&&['queued','running','cancelling'].includes(j.status))
 async function load(){const [r,t]=await Promise.all([fetch('/api/settings/availability'),api.tasks()]);if(!r.ok)throw new Error('Could not load availability settings');setData(await r.json());setTask(t.tasks.find((v:any)=>v.action==='availability'))}
 useEffect(()=>{void load().catch(e=>setError(e.message))},[revision])
 async function save(){setBusy(true);setError('');try{const r=await fetch('/api/settings/availability',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(data.settings)});if(!r.ok)throw new Error('Could not save availability settings');setData(await r.json());setNotice('Settings saved.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Media Availability</h2><p>Check Lidarr imports and find requested or missing tracks in Plex. An imported album does not confirm that the requested recording is available.</p>{error&&<ErrorNotice error={error}/ >}{!data?<p>Loading settings…</p>:<><div className="availability-options">{([['refresh_lidarr','Refresh Lidarr request and import status'],['retry_missing','Retry automatic matching for missing tracks'],['sync_automatic','Update affected Auto Sync playlists']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={data.settings[key]} disabled={busy} onChange={e=>setData({...data,settings:{...data.settings,[key]:e.target.checked}})}/>{label}</label>)}<label>Plex cache freshness<select value={data.settings.cache_minutes} onChange={e=>setData({...data,settings:{...data.settings,cache_minutes:Number(e.target.value)}})}>{[5,15,30,60].map(n=><option key={n} value={n}>{n} minutes</option>)}</select></label></div><p className="muted">Each availability scan refreshes Plex. Playlist syncs can reuse that snapshot within the selected interval. Manual matches are preserved; uncertain matches remain for review. Other affected playlists show Ready to Sync.</p><button disabled={busy} onClick={save}>Save Settings</button>{notice&&<p role="status">{notice}</p>}<h3>Schedule</h3>{task&&<label>Frequency<select disabled={busy} value={task.hours} onChange={async e=>{setBusy(true);try{await api.saveSchedule({action:'availability',scope:'all',hours:Number(e.target.value)},task.id);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{Object.entries({0:'Disabled',1:'Every hour',3:'Every 3 hours',6:'Every 6 hours',12:'Every 12 hours',24:'Daily'}).map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>}<p>Next run: {task?.next_run?new Date(task.next_run).toLocaleString():'Disabled'}</p><button disabled={active||busy} onClick={async()=>{setBusy(true);try{await api.enqueue('availability');window.dispatchEvent(new Event('jobs-refresh'));setNotice('Availability scan queued. View progress in Activity.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{active?'Scan queued / running…':'Scan Now'}</button><p className="muted">Runs align to midnight. Manual scans do not shift the schedule; overlapping runs are skipped.</p>{data.latest&&<><h3>Last completed scan</h3><p>{new Date(data.latest.checked_at*1000).toLocaleString()} · {data.latest.seconds}s</p><p>{data.latest.summary}</p>{data.latest.warnings?.map((w:string,i:number)=><ErrorNotice key={i} error={w}/>)}</>}</>}</section>
}
