import { useEffect, useRef } from 'react'
export function Icon({name}:{name:string}){
 const paths:Record<string,any>={discover:<><circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5Z"/></>,library:<><path d="M4 3v18M9 3v18M14 3v18m3-17 4 16"/></>,users:<><circle cx="9" cy="7" r="3"/><path d="M3 21v-4a6 6 0 0 1 12 0v4M17 4a3 3 0 0 1 0 6m1 4a5 5 0 0 1 3 5v2"/></>,account:<><circle cx="12" cy="7" r="4"/><path d="M4 22v-4a8 8 0 0 1 16 0v4"/></>,blocklist:<><circle cx="12" cy="12" r="9"/><path d="m6 6 12 12"/></>,requests:<><path d="M4 4h16v16H4zM8 9h8M8 13h5M8 17h3"/></>,edit:<><path d="m15 4 5 5M4 20l5-1L21 7l-5-5L4 14Z"/></>,activity:<><path d="M3 12h4l3-8 4 16 3-8h4"/></>,autosync:<><path d="M20 7a8 8 0 0 0-14-2L3 8m0-5v5h5M4 17a8 8 0 0 0 14 2l3-3m0 5v-5h-5"/></>,filter:<path d="M3 4h18l-7 8v7l-4 2V12Z"/>,sort:<><path d="M8 4v16m-4-4 4 4 4-4M16 20V4m-4 4 4-4 4 4"/></>,refresh:<><path d="M20 8a8 8 0 1 0 0 8M20 3v5h-5"/></>,compact:<><path d="M8 6h13M8 12h13M8 18h13M3 6h1M3 12h1M3 18h1"/></>,expanded:<><rect x="3" y="3" width="18" height="7" rx="2"/><rect x="3" y="14" width="18" height="7" rx="2"/></>,dashboard:<><path d="m3 10 9-7 9 7v11h-6v-7H9v7H3Z"/></>,playlists:<><path d="M9 17V5l11-2v12M9 8l11-2"/><ellipse cx="6" cy="18" rx="3" ry="2"/><ellipse cx="17" cy="16" rx="3" ry="2"/></>,missing:<><path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v1"/></>,search:<><circle cx="10" cy="10" r="7"/><path d="m15 15 6 6"/></>,settings:<><path d="m9 3-1 3-3 1-2 4 2 2v4l4 3 3-1 3 1 4-3v-4l2-2-2-4-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/></>,copy:<><rect x="8" y="8" width="12" height="13" rx="2"/><path d="M15 8V3H3v12h5"/></>,download:<><path d="M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5"/></>,raw:<><path d="m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18"/></>,sync:<><path d="m17 2 4 4-4 4M3 6h18M7 14l-4 4 4 4m14-4H3"/></>}
 return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]||paths.playlists}</svg>
}
function Menu({label,icon,badge,children}:{label:string;icon:string;badge?:number;children:React.ReactNode}){
 const ref=useRef<HTMLDetailsElement>(null)
 useEffect(()=>{const close=(e:Event)=>{if(e instanceof KeyboardEvent?e.key==='Escape':!ref.current?.contains(e.target as Node))ref.current?.removeAttribute('open')};document.addEventListener('click',close);document.addEventListener('keydown',close);return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',close)}},[])
 return <details className="control-menu" ref={ref}><summary title={label} aria-label={label}><Icon name={icon}/>{!!badge&&<span className="control-badge">{badge}</span>}</summary><div className="control-popover">{children}</div></details>
}
export function filterMatches(values:string[],predicate:(name:string)=>boolean,mode:'any'|'all'='any'){
 const included=values.filter(v=>!v.startsWith('!')),excluded=values.filter(v=>v.startsWith('!')).map(v=>v.slice(1))
 return !excluded.some(predicate)&&(!included.length||(mode==='all'?included.every(predicate):included.some(predicate)))
}
export function cycleFilter(value:string[],choice:string){const state=value.includes(choice)?1:value.includes('!'+choice)?2:0;return [...value.filter(v=>v!==choice&&v!=='!'+choice),...(state===0?[choice]:state===1?['!'+choice]:[])]}
export function FilterMenu({choices,value,onChange,labels={}}:{choices:string[];value:string[];onChange:(v:string[])=>void;labels?:Record<string,string>}){return <Menu label={`Filters${value.length?` (${value.length} active)`:''}`} icon="filter" badge={value.length}><strong>Filters</strong><small>Click to include, again to exclude, again to clear.</small>{choices.map(choice=>{const included=value.includes(choice),excluded=value.includes('!'+choice);return <button type="button" role="checkbox" aria-checked={excluded?'mixed':included} className={`filter-choice ${excluded?'excluded':''}`} key={choice} onClick={()=>onChange(cycleFilter(value,choice))}><span aria-hidden="true">{excluded?'−':included?'✓':'□'}</span> {excluded?'Not ':''}{labels[choice]||choice}</button>})}<button className="clear-button" disabled={!value.length} onClick={()=>onChange([])}>Clear Filters</button></Menu>}
export function SortMenu({choices,value,onChange}:{choices:Record<string,string>;value:string;onChange:(v:string)=>void}){
 const fields=new Map<string,{key:string;label:string}>()
 const names:Record<string,string>={name:'Name',title:'Track title',artist:'Artist',album:'Album',order:'Source order',last_synced:'Last synced',unresolved:'Missing tracks',last_checked:'Last checked',occurrence_count:'Occurrences',playlist_count:'Playlist count',occurrences:'Occurrences'}
 Object.entries(choices).forEach(([key,label])=>{const field=key.split(':')[0];if(!fields.has(field))fields.set(field,{key,label:names[field]||label})})
 const field=value.split(':')[0],base=fields.get(field)?.key||value,defaultDirection=base.split(':')[1]||'asc',direction=value.split(':')[1]||defaultDirection,reversed=direction!==defaultDirection
 return <Menu label="Sort" icon="sort"><strong>Sort by</strong>{Array.from(fields,([f,item])=><label key={f}><input type="radio" name="sort" checked={field===f} onChange={()=>onChange(item.key)}/>{item.label}</label>)}<label className={reversed?'reverse-sort active':'reverse-sort'}><input type="checkbox" checked={reversed} onChange={()=>onChange(`${field}:${direction==='asc'?'desc':'asc'}`)}/>Reverse sort</label></Menu>
}
export function FilterChips({value,onChange,labels={}}:{value:string[];onChange:(v:string[])=>void;labels?:Record<string,string>}){return value.length?<div className="filter-chips">{value.map(v=><button className={v.startsWith('!')?'excluded':''} key={v} onClick={()=>onChange(value.filter(f=>f!==v))}>{v.startsWith('!')?'Not ':''}{labels[v.replace(/^!/, '')]||v.replace(/^!/, '')} ×</button>)}<button className="clear-button" onClick={()=>onChange([])}>Clear</button></div>:null}
export const trackLink=(t:{title:string;artist:string;album?:string})=>`#track/${encodeURIComponent(JSON.stringify({title:t.title,artist:t.artist,album:t.album||''}))}`
