import {useEffect,useState} from 'react'
import {request} from './api'
import {AddLidarrAlbum} from './Lidarr'
import ErrorNotice from './ErrorNotice'
import {useAccount} from './Auth'
import Modal from './Modal'
export function UserAlbumRequest({track,onClose}:{track:any;onClose:()=>void}){
 const [title,setTitle]=useState(track.title||''),[artist,setArtist]=useState(track.artist||''),[album,setAlbum]=useState(track.album||''),[rows,setRows]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 async function search(){setBusy(true);setError('');try{const d=await request<any>('/api/requests-user/search',{method:'POST',body:JSON.stringify({artist,album,title})});setRows(d.rows)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{void search()},[])
 async function add(){setBusy(true);try{await request('/api/requests-user/add',{method:'POST',body:JSON.stringify({album_id:selected.album_id})});setMessage('Album requested. View its status in Requests.');setSelected(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <Modal onClose={onClose}><div className="modal" role="dialog" aria-modal="true" aria-label="Request album"><div className="modal-header"><h2>Request Album</h2><button onClick={onClose}>×</button></div><div className="modal-body">{error&&<ErrorNotice error={error}/>}<p role="status">{message}</p><form onSubmit={e=>{e.preventDefault();void search()}}><label>Artist<input value={artist} onChange={e=>setArtist(e.target.value)}/></label><label>Album<input value={album} onChange={e=>setAlbum(e.target.value)}/></label><label>Song<input value={title} onChange={e=>setTitle(e.target.value)}/></label><button disabled={busy}>Find albums</button></form>{busy&&<p>Working…</p>}{rows.map(r=><button className={`candidate ${selected?.album_id===r.album_id?'chosen':''}`} key={r.album_id} onClick={()=>setSelected(r)}>{r.artwork&&<img className="album-artwork" src={r.artwork} alt=""/>}<span><strong>{r.title}</strong><small>{r.artist} · {r.year||'Year unknown'}</small></span></button>)}</div><div className="modal-footer"><button onClick={onClose}>Close</button><button disabled={busy||!selected} onClick={add}>Request selected album</button></div></div></Modal>
}
export default function Discover({initialQuery=''}:{initialQuery?:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[q,setQ]=useState(initialQuery),[username,setUsername]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<any>(null)
 const user=useAccount()
 async function load(importUser=false){setBusy(true);setError('');try{setData(await request(`/api/discover?${importUser?'username='+encodeURIComponent(username):'q='+encodeURIComponent(q)}`))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{void load()},[])
 return <><section className="panel"><details><summary>Explore your Last.fm albums</summary><form className="add" onSubmit={e=>{e.preventDefault();void load(true)}}><input aria-label="Last.fm username" placeholder="Last.fm username" value={username} onChange={e=>setUsername(e.target.value)}/><button disabled={busy||!username}>Review albums</button></form><p>This checks your top albums against the saved library. Nothing is requested automatically.</p></details>{error&&<ErrorNotice error={error}/>}</section>{busy&&<p role="status">Finding albums…</p>}<h2>{data?.heading}</h2><div className="discover-grid">{data?.rows.map((a:any)=><article className="panel" key={`${a.artist}-${a.album}`}>{a.artwork&&<img src={a.artwork} alt="" loading="lazy"/>}<h3>{a.album}</h3><p>{a.artist}</p><p>{a.availability}</p><button disabled={!user?.can_request&&!user?.admin} onClick={()=>setSelected({title:'',artist:a.artist,album:a.album})}>Review / Request</button></article>)}</div>{data&&<p><a href="https://www.last.fm" target="_blank" rel="noreferrer">Powered by Last.fm</a> · Availability reflects the latest completed scans.</p>}{selected&&<AddLidarrAlbum track={selected} onClose={()=>setSelected(null)}/>}</>
}
export function UserRequests(){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');const load=()=>request<any[]>('/api/requests-user').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);return <section className="panel"><div className="panel-head"><h2>Your requests</h2><button onClick={load}>Refresh</button></div>{error&&<ErrorNotice error={error}/>} {rows.map(r=><article key={r.album_id}><h3>{r.title} — {r.artist}</h3><p>{r.display_status}{r.percent!=null?` · ${r.percent}%`:''}</p></article>)}{!rows.length&&<p>No album requests yet.</p>}</section>}
export function Users(){const [rows,setRows]=useState<any[]>([]),[error,setError]=useState('');const load=()=>request<any[]>('/api/users').then(setRows).catch(e=>setError(e.message));useEffect(()=>{void load()},[]);async function change(u:any,key:string,value:boolean){try{await request('/api/users/'+u.id,{method:'PUT',body:JSON.stringify({disabled:u.disabled||false,can_request:u.can_request||false,[key]:value})});await load()}catch(e:any){setError(e.message)}}return <section className="panel"><h2>Users</h2>{error&&<ErrorNotice error={error}/>}<p>Accounts appear after signing in with Plex. The server owner controls requests and access.</p>{rows.map(u=><article key={u.id}><h3>{u.name}{u.admin?' · Administrator':''}</h3>{!u.admin&&<div className="actions"><label><input type="checkbox" checked={u.can_request} onChange={e=>change(u,'can_request',e.target.checked)}/>Allow requests</label><label><input type="checkbox" checked={u.disabled} onChange={e=>change(u,'disabled',e.target.checked)}/>Disable account</label></div>}</article>)}</section>}
export function LastfmSettings(){const [key,setKey]=useState(''),[message,setMessage]=useState('');return <section className="panel"><h2>Last.fm</h2><p>Add the server API key to enable Discover. It is shared across users and never returned to the browser.</p><form onSubmit={async e=>{e.preventDefault();try{await request('/api/settings/lastfm',{method:'PUT',body:JSON.stringify({api_key:key})});setKey('');setMessage('Saved.')}catch(e:any){setMessage(e.message)}}}><label>API key<input type="password" autoComplete="off" value={key} onChange={e=>setKey(e.target.value)} placeholder="Leave blank to keep saved key"/></label><button>Save</button></form><p role="status">{message}</p></section>}
