import {useEffect,useState} from 'react'
import {request} from './api'
import ErrorNotice from './ErrorNotice'
import {stamp} from './HealthCard'
export default function Library(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[open,setOpen]=useState('')
 const load=()=>request<any>('/api/library').then(setData).catch(e=>setError(e.message))
 useEffect(()=>{void load()},[])
 const labels:any={linked:'Linked',attention:'Needs Attention',review:'Needs Review',lidarr_only:'Lidarr only',pending:'Scan pending'}
 const rows=(data?.rows||[]).filter((r:any)=>(filter==='all'||r.status===filter)&&`${r.artist} ${r.album}`.toLowerCase().includes(query.toLowerCase()))
 return <section className="panel"><div className="panel-head"><h2>Library connections</h2><button onClick={load}>Refresh view</button></div><p>Compare the saved Plex and Lidarr inventories. Scans run from Settings → Tasks.</p>{error&&<ErrorNotice error={error}/>}<div className="actions"><input aria-label="Filter library" placeholder="Artist or album" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Library status" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All albums</option>{Object.entries(labels).map(([k,v])=><option key={k} value={k}>{String(v)}</option>)}</select></div>{!data?<p role="status">Loading library…</p>:<><p className="muted">Plex scan: {data.plex_checked_at?stamp(new Date(data.plex_checked_at*1000).toISOString()):'Not scanned'} · Lidarr scan: {data.lidarr_checked_at?stamp(new Date(data.lidarr_checked_at*1000).toISOString()):'Not scanned'}</p>{!data.scans_complete&&<p role="status">Both scans must complete before missing albums are flagged.</p>}<p>{rows.length} albums · {data.note}</p>{rows.map((r:any)=><article className="playlist-card" key={r.id}><div className="panel-head"><div><h3>{r.album}</h3><p>{r.artist}</p></div><button className={r.status==='attention'?'health-error':''} onClick={()=>setOpen(open===r.id?'':r.id)} aria-expanded={open===r.id}>{labels[r.status]}</button></div><p>{r.reason} · {r.plex_tracks} Plex tracks{r.expected_tracks?` / ${r.expected_tracks} expected`:''}{r.completeness==='incomplete'?' · Incomplete':''}</p>{open===r.id&&<div><div className="actions">{r.plex_url&&<a href={r.plex_url} target="_blank" rel="noreferrer">Open in Plex ↗</a>}{r.lidarr_url&&<a href={r.lidarr_url} target="_blank" rel="noreferrer">Open in Lidarr ↗</a>}</div>{r.tracks.map((t:any)=><p key={t.plex_id}>{t.title} — {t.artist}</p>)}{!r.tracks.length&&<p>No Plex tracks in the last scan.</p>}</div>}</article>)}{!rows.length&&<p>No albums match this view.</p>}</>}</section>
}
