import {useEffect,useState} from 'react'
import {request} from './api'
import ErrorNotice from './ErrorNotice'
import {FilterMenu,SortMenu,FilterChips,filterMatches,Icon} from './Controls'
import Modal from './Modal'
export default function Library(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[filters,setFilters]=useState<string[]>([]),[sort,setSort]=useState('artist:asc'),[artist,setArtist]=useState(''),[album,setAlbum]=useState<any>(null),[tab,setTab]=useState('library'),[link,setLink]=useState<any>(null),[candidates,setCandidates]=useState<any[]>([]),[search,setSearch]=useState('')
 const load=()=>request<any>('/api/library').then(setData).catch(e=>setError(e.message))
 useEffect(()=>{void load()},[])
 async function open(id:string){try{setAlbum(await request('/api/library/albums/'+encodeURIComponent(id)))}catch(e:any){setError(e.message)}}
 async function find(q:string){setSearch(q);try{setCandidates(await request<any[]>('/api/library/plex-tracks?q='+encodeURIComponent(q)))}catch(e:any){setError(e.message)}}
 async function save(id:string|null){try{await request('/api/library/tracks/'+link.id+'/link',{method:'PUT',body:JSON.stringify({plex_id:id})});setLink(null);await open(album.album_id);await load()}catch(e:any){setError(e.message)}}
 const [field,direction]=sort.split(':')
 const rows=(data?.rows||[]).filter((r:any)=>(!artist||r.artist===artist)&&filterMatches(filters,f=>r.status===f)&&`${r.artist} ${r.title}`.toLowerCase().includes(query.toLowerCase())).sort((a:any,b:any)=>String(a[field]||'').localeCompare(String(b[field]||''))*(direction==='desc'?-1:1))
 const artists=[...new Set<string>(rows.map((r:any)=>r.artist))]
 return <><section className="panel"><div className="panel-head"><h2>{album?album.title:artist||'Music Library'}</h2><button onClick={()=>{void load();if(album)void open(album.album_id)}} aria-label="Refresh library"><Icon name="refresh"/></button></div><p>Your Lidarr collection, with Plex playback links. Library scans update this view.</p><div className="actions"><button onClick={()=>{setTab('library');setAlbum(null)}}>Library</button><button onClick={()=>{setTab('errors');setAlbum(null)}}>Needs Attention ({data?.errors.length||0})</button>{(artist||album)&&<button onClick={()=>{album?setAlbum(null):setArtist('')}}>← Back</button>}</div>{error&&<ErrorNotice error={error}/ >}{!data&&<p>Loading library…</p>}{data&&!data.tracks_scanned&&<p role="status">Run a Lidarr Library Scan in Settings → Tasks to populate track identities and links.</p>}{!album&&<><input placeholder="Filter artists or albums" aria-label="Filter library" value={query} onChange={e=>setQuery(e.target.value)}/>{tab==='library'&&<div className="actions"><FilterMenu choices={['Available','Partially Available','Downloading','Awaiting Download','Awaiting Plex','Scan pending']} value={filters} onChange={setFilters}/><SortMenu choices={{'artist:asc':'Artist','title:asc':'Album','status:asc':'Status'}} value={sort} onChange={setSort}/></div>}<FilterChips value={filters} onChange={setFilters}/></>}</section>
 {tab==='errors'?<section className="panel">{data?.errors.filter((t:any)=>`${t.artist} ${t.album} ${t.title}`.toLowerCase().includes(query.toLowerCase())).map((t:any)=><article className="missing-row" key={t.plex_id}><div><strong>{t.title}</strong><small>{t.artist} · {t.album}</small><p>{t.reason}</p></div></article>)}{data&&!data.errors.length&&<p>No unlinked Plex tracks in the current scan.</p>}</section>:album?<section className="panel"><div className="actions"><a href={album.lidarr_url} target="_blank" rel="noreferrer">Open in Lidarr ↗</a><a href={'https://musicbrainz.org/release-group/'+album.album_id} target="_blank" rel="noreferrer">MusicBrainz ↗</a></div><h3>{album.artist}</h3><p>{album.monitored?'Monitored':'Not monitored'} · {album.statistics?.trackFileCount||0} files in Lidarr</p><h4>Selected release</h4>{(album.releases||[]).filter((r:any)=>r.monitored).map((r:any)=><p key={r.id}>{r.title} · {r.releaseDate||'Year unknown'} · {r.trackCount} tracks</p>)}{album.tracks.map((t:any)=><article className="missing-row" key={t.id}><div className="grow"><strong>{t.track_number}. {t.title}</strong><small>{t.link?`Linked to Plex · ${t.link.method}`:t.file?'Awaiting Plex / link review':'Awaiting Download'}</small>{t.plex&&<small>Plex: {t.plex.title} · {t.plex.album}</small>}</div><button disabled={!t.file} onClick={()=>{setLink(t);void find(t.title)}}>Review Link</button></article>)}</section>:<>{!artist&&!query&&field==='artist'&&<div className="discover-grid">{artists.map(a=><button className="panel" key={a} onClick={()=>setArtist(a)}><h3>{a}</h3><p>{rows.filter((r:any)=>r.artist===a).length} albums</p></button>)}</div>}{(artist||query||field!=='artist')&&<div className="discover-grid">{rows.map((r:any)=><button className="panel album-card" key={r.album_id} onClick={()=>open(r.album_id)}>{r.artwork&&<img src={r.artwork} alt="" loading="lazy"/>}<h3>{r.title}</h3><p>{r.artist}</p><p>{r.status} · {r.plex_count}/{r.track_count} tracks linked</p></button>)}</div>}{data&&!rows.length&&<p>No albums match this view.</p>}</>}
 {link&&<Modal onClose={()=>setLink(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Review track association"><div className="modal-header"><h2>Link {link.title} to Plex</h2><button onClick={()=>setLink(null)}>Close</button></div><div className="modal-body"><p>Choose the same recording and edition. This sets a library association; existing playlist manual matches remain unchanged.</p><form onSubmit={e=>{e.preventDefault();void find(search)}}><input value={search} onChange={e=>setSearch(e.target.value)} aria-label="Search Plex tracks"/><button>Search</button></form>{candidates.map(t=><button className="candidate" key={t.plex_id} onClick={()=>save(t.plex_id)}>{t.title} — {t.artist} · {t.album}</button>)}</div><div className="modal-footer"><button onClick={()=>save(null)}>Use Automatic Link</button></div></section></Modal>}</>
}
