import ErrorNotice from './ErrorNotice'
import {mbCall,mbLookup,MBSettings} from './MusicBrainz'
import { useEffect, useRef, useState } from 'react'
import Modal from './Modal'
import { api, MissingTrack } from './api'

type Defaults={root_folder:string;quality_profile_id:number;metadata_profile_id:number;monitor:string;monitor_new:string;monitor_album:boolean;search_now:boolean;tags:number[];tag_existing:boolean}
type Settings=Defaults&{enabled:boolean;url:string;api_key:string;api_key_saved?:boolean;musicbrainz_enabled:boolean;cache_days:number;cache_entries?:number}
type Root={id:number;path:string;defaultQualityProfileId?:number;defaultMetadataProfileId?:number;defaultMonitorOption?:string;defaultNewItemMonitorOption?:string;defaultTags?:number[]}
type Options={version:string;roots:Root[];tags:{id:number;label:string}[];qualities:{id:number;name:string}[];metadata:{id:number;name:string}[]}
type Album={artwork?:string;album_id:string;title:string;artist:string;year:string;type:string;secondary_types:string[];exists:boolean|null;monitored?:boolean|null;lidarr_id?:number}
type Preview={preview_id:string;album:Album;artist_exists:boolean;album_exists:boolean;album_monitored:boolean;defaults:Defaults;quality:string;metadata:string;tags:string[]}
const monitorLabels:Record<string,string>={selected:'Only the selected album',all:'All albums',future:'Future albums',missing:'Missing albums',existing:'Albums with files',none:'None'}
const defaults:Settings={enabled:false,url:'',api_key:'',root_folder:'',quality_profile_id:0,metadata_profile_id:0,monitor:'selected',monitor_new:'none',monitor_album:true,search_now:false,musicbrainz_enabled:true,cache_days:7,tags:[],tag_existing:false}
const noOptions:Options={version:'',roots:[],qualities:[],metadata:[],tags:[]}
async function call<T>(path:string,method='GET',body?:unknown):Promise<T>{
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000)
 try{const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check the selected settings and try again.');return data}
 catch(e:any){if(e.name==='AbortError')throw new Error('Lidarr request timed out. Check its connection before retrying.');throw e}finally{clearTimeout(timer)}
}
function rootDefaults(value:Defaults,root:Root):Defaults{
 const monitor=root.defaultMonitorOption&&monitorLabels[root.defaultMonitorOption]?root.defaultMonitorOption:value.monitor
 return {...value,root_folder:root.path,quality_profile_id:root.defaultQualityProfileId??value.quality_profile_id,metadata_profile_id:root.defaultMetadataProfileId??value.metadata_profile_id,monitor,monitor_new:root.defaultNewItemMonitorOption||value.monitor_new,monitor_album:monitor!=='none',search_now:monitor==='none'?false:value.search_now,tags:root.defaultTags||[]}
}
function DefaultFields({value,options,onChange,createTag,disabled=false}:{value:Defaults;options:Options;onChange:(v:Defaults)=>void;createTag:(label:string)=>Promise<void>;disabled?:boolean}){
 const [tag,setTag]=useState(''),[tagBusy,setTagBusy]=useState(false),[tagError,setTagError]=useState('')
 const set=(key:string,v:unknown)=>onChange({...value,[key]:v})
 async function addTag(){if(tagBusy||!tag.trim())return;setTagBusy(true);setTagError('');try{await createTag(tag.trim().toLowerCase());setTag('')}catch(e:any){setTagError(e.message)}finally{setTagBusy(false)}}
 return <fieldset disabled={disabled} className="lidarr-fields"><div className="form-grid">
 <label>Root folder<select value={value.root_folder} onChange={e=>{const root=options.roots.find(r=>r.path===e.target.value);onChange(root?rootDefaults(value,root):{...value,root_folder:''})}}><option value="">Select root folder</option>{options.roots.map(r=><option key={r.id} value={r.path}>{r.path}</option>)}</select></label>
 <label>Quality profile<select value={value.quality_profile_id} onChange={e=>set('quality_profile_id',Number(e.target.value))}><option value={0}>Select quality profile</option>{options.qualities.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>Metadata profile<select value={value.metadata_profile_id} onChange={e=>set('metadata_profile_id',Number(e.target.value))}><option value={0}>Select metadata profile</option>{options.metadata.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>Albums to monitor for new artists<select value={value.monitor} onChange={e=>onChange({...value,monitor:e.target.value,...(e.target.value==='none'?{monitor_album:false,search_now:false}:e.target.value==='selected'?{monitor_album:true}:{})})}>{Object.entries(monitorLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label>New releases discovered later<select value={value.monitor_new} onChange={e=>set('monitor_new',e.target.value)}><option value="none">Do not monitor</option><option value="new">New releases only</option><option value="all">All newly discovered albums</option></select></label>
 <div className="lidarr-tag-field"><label>Artist tags<div className="lidarr-tag-entry"><input aria-label="New artist tag" placeholder="Enter your tag" maxLength={64} value={tag} onChange={e=>setTag(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addTag()}}}/><button type="button" disabled={tagBusy||!tag.trim()} onClick={addTag}>{tagBusy?'Adding…':'Create & Add'}</button></div></label><div className="filter-chips">{value.tags.map(id=><button type="button" key={id} aria-label={`Remove tag ${options.tags.find(t=>t.id===id)?.label||id}`} onClick={()=>set('tags',value.tags.filter(t=>t!==id))}>{options.tags.find(t=>t.id===id)?.label||`Saved tag ${id}`} ×</button>)}</div>{tagError&&<ErrorNotice error={tagError}/>}</div>
 </div><button type="button" disabled={!options.roots.find(r=>r.path===value.root_folder)?.defaultMetadataProfileId} onClick={()=>{const root=options.roots.find(r=>r.path===value.root_folder);if(root)onChange(rootDefaults(value,root))}}>Use Root Folder Defaults</button><p className="muted">Choosing a root folder loads its defaults. A metadata profile named None is valid and separate from monitoring None.</p><label className="playlist-choice"><input type="checkbox" checked={value.monitor_album} onChange={e=>onChange({...value,monitor_album:e.target.checked,...(!e.target.checked?{search_now:false,...(value.monitor==='selected'?{monitor:'none'}:{})}:value.monitor==='none'?{monitor:'selected'}:{})})}/> Monitor the selected album</label>
 <label className="playlist-choice"><input type="checkbox" checked={value.search_now} disabled={!value.monitor_album} onChange={e=>set('search_now',e.target.checked)}/> Search immediately for the selected album</label>
 <label className="playlist-choice"><input type="checkbox" checked={value.tag_existing} onChange={e=>set('tag_existing',e.target.checked)}/> Also add these tags to existing artists (keep their other tags)</label>
 </fieldset>
}
export default function LidarrSettings(){
 const [value,setValue]=useState<Settings>(defaults),[options,setOptions]=useState<Options>(noOptions),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{let active=true;call<Settings>('/api/settings/lidarr').then(s=>{if(active){setValue({...defaults,...s,api_key:''});setLoaded(true);if(s.url&&s.api_key_saved)call<Options['tags']>('/api/settings/lidarr/tags').then(tags=>{if(active){setOptions(o=>({...o,tags}));const missing=s.tags.filter(id=>!tags.some(t=>t.id===id));if(missing.length)setError(`Saved tags no longer found in Lidarr: ${missing.join(', ')}. Remove or recreate them.`)}}).catch(e=>{if(active)setError(`Could not load saved tag names: ${e.message}`)})}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 async function discover(){setBusy(true);setError('');setMessage('Connecting to Lidarr and loading profiles…');try{const result=await call<Options>('/api/settings/lidarr/test','POST',value);setOptions(result);setMessage(`Connected to Lidarr ${result.version}. Root folders and profiles loaded.`)}catch(e:any){setError(e.message);setMessage('')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');setMessage('Saving settings…');try{const result=await call<Settings>('/api/settings/lidarr','PUT',value);setValue({...defaults,...result,api_key:'',cache_entries:value.cache_entries});setMessage('Lidarr settings saved.')}catch(e:any){setError(e.message);setMessage('')}finally{setBusy(false)}}
 const displayOptions={...options,roots:options.roots.length?options.roots:value.root_folder?[{id:-1,path:value.root_folder}]:[],qualities:options.qualities.length?options.qualities:value.quality_profile_id?[{id:value.quality_profile_id,name:`Saved profile (${value.quality_profile_id}) — connect to load names`}]:[],metadata:options.metadata.length?options.metadata:value.metadata_profile_id?[{id:value.metadata_profile_id,name:`Saved profile (${value.metadata_profile_id}) — connect to load names`}]:[]}
 return <section className="panel settings-panel"><h2>Lidarr</h2><p className="muted">Add albums from Missing after reviewing each selection.</p>{!loaded&&!error&&<p>Loading settings…</p>}
 <fieldset disabled={!loaded||busy} className="lidarr-fields"><label className="playlist-choice"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/> Enable Lidarr integration</label><div className="form-grid">
 <label>Lidarr URL<input value={value.url} placeholder="http://lidarr:8686" onChange={e=>{setValue({...value,url:e.target.value});setOptions(noOptions)}}/></label>
 <label>API key<input type="password" autoComplete="new-password" value={value.api_key} placeholder={value.api_key_saved?'Saved — leave blank to keep':'Enter Lidarr API key'} onChange={e=>setValue({...value,api_key:e.target.value})}/></label></div><button type="button" onClick={discover} disabled={!value.url}>Test Connection & Load Profiles</button>
 <h3>Album defaults</h3><DefaultFields value={value} options={displayOptions} onChange={v=>setValue({...value,...v})} createTag={async label=>{const tag=await call<{id:number;label:string}>('/api/settings/lidarr/tag','POST',{...value,label});setOptions(o=>({...o,tags:[...o.tags.filter(t=>t.id!==tag.id),tag]}));setValue(v=>({...v,tags:Array.from(new Set([...v.tags,tag.id]))}));setMessage('Tag created and added. Save Changes to keep it as an album default.')}}/><p className="muted">Root folder, profiles and artist-wide monitoring apply to new artists. Existing artists keep their Lidarr settings; existing monitored albums stay monitored.</p>

 <p><a href="#settings/musicbrainz">MusicBrainz lookup, release priority and retry settings →</a></p>
 <div className="settings-save"><button className="primary" type="button" onClick={save}>Save Changes</button></div></fieldset>
 {message&&<p role="status">{message}</p>}{error&&<ErrorNotice error={error}/>}</section>
}
export function AddLidarrAlbum({track,onClose,sourceTrack=track,searchQuery}:{searchQuery?:string;track:Pick<MissingTrack,'title'|'artist'|'album'>;sourceTrack?:Pick<MissingTrack,'title'|'artist'|'album'>;onClose:()=>void}){
 const unknownAlbum=!track.album||['n/a','unknown'].includes(track.album.trim().toLowerCase())
 const [appleRows,setAppleRows]=useState<any[]|null>(null),[lookupAlbum,setLookupAlbum]=useState('')
 const initialQuery=searchQuery??(track.album&&!['n/a','unknown'].includes(track.album.toLowerCase())?`${track.artist} - ${track.album}`:`${track.artist} - ${track.title}`)
 const [settings,setSettings]=useState<Settings|null>(null),[options,setOptions]=useState<Options>(noOptions),[value,setValue]=useState<Defaults>(defaults)
 const [query,setQuery]=useState(initialQuery),[rows,setRows]=useState<Album[]>([]),[selected,setSelected]=useState<Album|null>(null),[message,setMessage]=useState('Loading album options…'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false)
 const [bypass,setBypass]=useState(false)
 const [mbFields,setMbFields]=useState({title:track.title||'',artist:track.artist||'',album:unknownAlbum?'':(track.album||'')})
 const [mb,setMb]=useState<MBSettings|null>(null),[mbFailed,setMbFailed]=useState(false)
 const generation=useRef(0),searching=useRef(false),submitting=useRef(false)
 useEffect(()=>{const g=++generation.current;(async()=>{try{
  const s=await call<Settings>('/api/settings/lidarr');if(g!==generation.current)return;setSettings({...s,api_key:''});setValue(s)
  const prefs=await mbCall<MBSettings>('/api/settings/musicbrainz');if(g!==generation.current)return;setMb(prefs)
  if(!s.enabled){setMessage('Configure and enable Lidarr first.');return}
  const o=await call<Options>('/api/settings/lidarr/test','POST',{...s,api_key:''});if(g!==generation.current)return;setOptions(o)
  setMessage('Searching Lidarr for this track’s album…')
  const result=await call<{rows:Album[]}>('/api/lidarr/search','POST',{...track,query:initialQuery,provider:'lidarr'});if(g!==generation.current)return
  setRows(result.rows);setMessage(`${result.rows.length} album candidates. Choose the album and recording version you want.`)
 }catch(e:any){if(g===generation.current){setError(e.message);setMessage('Could not complete the initial search. You can search again below.')}}finally{if(g===generation.current)setBusy(false)}})();return()=>{generation.current++}},[])
 async function search(provider:string,single=false,queryOverride?:string){if(searching.current||saving)return;searching.current=true;const g=++generation.current;setMbFailed(false);setBusy(true);setError('');setSelected(null);setMessage(provider==='musicbrainz'?'Finding albums with MusicBrainz…':'Searching Lidarr…');try{
  const body={...track,album:lookupAlbum||track.album,...(provider==='musicbrainz'?{...mbFields,fields_search:true}:{}),query:queryOverride??query,provider,force_refresh:single||bypass};const result=provider==='musicbrainz'?await mbLookup<{rows:Album[];provider:string;cached:boolean}>(body,single?0:mb?.retries??2,m=>{if(g===generation.current)setMessage(m)},()=>g===generation.current):await call<{rows:Album[];provider:string;cached:boolean}>('/api/lidarr/search','POST',body)
  if(g!==generation.current)return;setRows(result.rows);setMessage(`${result.rows.length} album candidates · ${result.provider}${result.cached?' · cached':''}. Choose the album you want.`)
 }catch(e:any){if(g===generation.current){setError(e.message);setMessage(rows.length?'Previous results are still shown.':'');setMbFailed(provider==='musicbrainz')}}finally{searching.current=false;if(g===generation.current)setBusy(false)}}
 async function findAppleAlbums(){if(busy||saving)return;const g=++generation.current;setBusy(true);setError('');setMessage('Finding possible albums in Apple Music…');try{const result=await api.applePreview(track);if(g!==generation.current)return;const unique=Array.from(new Map(result.rows.filter((r:any)=>r.album).map((r:any)=>[`${r.artist}|${r.album}`,r])).values());setAppleRows(unique);setMessage(unique.length?'Choose an Apple Music suggestion to search Lidarr. Check the track and artist before choosing.':'No Apple Music album suggestions found. Try Advanced Lookup.')}catch(e:any){if(g===generation.current)setError(e.message)}finally{if(g===generation.current)setBusy(false)}}
 async function searchExisting(a:Album){if(submitting.current)return;submitting.current=true;setSaving(true);setError('');try{await call('/api/lidarr/search-existing','POST',{album_id:a.album_id,source_title:sourceTrack.title,source_artist:sourceTrack.artist});window.dispatchEvent(new CustomEvent('bridge-notice',{detail:`Search queued in Lidarr: ${a.title}. Progress is available in Activity.`}));window.dispatchEvent(new Event('lidarr-requested'));onClose()}catch(e:any){setError(e.message)}finally{submitting.current=false;setSaving(false)}}
 async function add(){if(!selected||submitting.current)return;submitting.current=true;setSaving(true);setError('');setMessage('Checking the selected album and queuing your request…');try{
  const preview=await call<Preview>('/api/lidarr/preview','POST',{...value,album_id:selected.album_id})
  await call('/api/lidarr/add','POST',{preview_id:preview.preview_id,source_title:sourceTrack.title,source_artist:sourceTrack.artist})
  window.dispatchEvent(new CustomEvent('bridge-notice',{detail:`Requested in Lidarr: ${selected.title}. Progress is available in Activity.`}))
  window.dispatchEvent(new Event('lidarr-requested'));onClose()
 }catch(e:any){setError(e.message);setMessage('Request could not be completed. Check the error before retrying.')}finally{submitting.current=false;setSaving(false)}}
 return <Modal onClose={onClose} busy={saving}><div className="modal match-dialog" role="dialog" aria-modal="true" aria-labelledby="lidarr-album-title"><div className="modal-header"><h2 id="lidarr-album-title">Add Album to Lidarr</h2><button disabled={saving} onClick={onClose} aria-label="Close album options">✕</button></div><div className="modal-body"><h3>{searchQuery!==undefined?'Find an album':`${track.title} — ${track.artist}`}</h3>{message&&<p role="status">{(busy||saving)&&<span className="spinner"/>}{message}</p>}{error&&<ErrorNotice error={error}/>}
 {settings&&!settings.enabled?<p><a href="#settings/lidarr" onClick={onClose}>Open Lidarr settings</a></p>:settings&&<>
 <form className="add" onSubmit={e=>{e.preventDefault();search('lidarr')}}><input disabled={saving} aria-label="Search Lidarr albums" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Album, track and artist, or lidarr:MusicBrainz-ID"/><button disabled={busy||saving||!query.trim()}>Search Albums</button></form><details className="lidarr-options"><summary>Advanced Lookup · MusicBrainz</summary>
 <p className="muted">Search using the fields below. Clear any field to leave it out. For soundtrack or compilation album searches, clear Recording and Artist to search by Album alone.</p>
 <form onSubmit={e=>{e.preventDefault();void search('musicbrainz')}}><div className="mb-search-fields">{([['title','Recording'],['artist','Artist'],['album','Album']] as const).map(([key,label])=><label key={key}>{label}<input disabled={busy||saving} value={mbFields[key]} onChange={e=>{setMbFields(v=>({...v,[key]:e.target.value}));setMbFailed(false)}}/></label>)}</div><button disabled={busy||saving||!mb?.enabled||!Object.values(mbFields).some(v=>v.trim())}>Search MusicBrainz</button>{mbFailed&&<button type="button" disabled={busy||saving} onClick={()=>search('musicbrainz',true)}>Retry Once</button>}</form></details>
 {unknownAlbum&&searchQuery===undefined&&<div className="apple-album-suggestions"><button disabled={busy||saving} onClick={findAppleAlbums}>Find Album with Apple Music</button>{appleRows&&<><p className="muted">Possible albums, not confirmed matches. Choosing one changes this search only.</p><div className="song-preview-choices">{appleRows.map(r=><button key={`${r.artist}|${r.album}`} className="candidate" disabled={busy||saving} onClick={()=>{const q=`${r.artist} - ${r.album}`;setQuery(q);setLookupAlbum(r.album);void search('lidarr',false,q)}}><span><strong>{r.album}</strong><small>{r.title} — {r.artist}</small></span><span>Search Lidarr</span></button>)}</div></>}</div>}
 <label className="playlist-choice"><input type="checkbox" checked={bypass} disabled={busy||saving} onChange={e=>setBypass(e.target.checked)}/> Bypass cache</label><small className="muted">Fetch fresh results from the service. Lidarr searches already bypass Bridge’s cache.</small>
 <div className="lidarr-candidates" aria-busy={busy}>{rows.map(a=><button disabled={busy||saving} className={`candidate ${selected?.album_id===a.album_id?'chosen':''}`} aria-pressed={selected?.album_id===a.album_id} key={a.album_id} onClick={()=>setSelected(a)}>{a.artwork&&<img className="album-artwork" src={a.artwork} alt="" loading="lazy" referrerPolicy="no-referrer" onError={e=>{e.currentTarget.style.display='none'}}/>}<span><strong>{a.title}</strong><small>{a.artist} · {a.year||'Year unknown'} · {[a.type,...a.secondary_types].filter(Boolean).join(', ')}</small>{a.exists&&<small>Already in Lidarr · {a.monitored?'Monitored':'Not monitored'}</small>}</span></button>)}</div>
 {selected&&<><h3>{selected.title}</h3>{selected.exists&&<p>Already in Lidarr · {selected.monitored?'Monitored':'Not monitored'}. <button disabled={busy||saving} onClick={()=>searchExisting(selected)}>Search Album</button></p>}<details className="lidarr-options"><summary>Options · using your saved defaults</summary><DefaultFields value={value} options={options} onChange={setValue} disabled={busy||saving} createTag={async label=>{const tag=await call<{id:number;label:string}>('/api/settings/lidarr/tag','POST',{...settings,label});setOptions(o=>({...o,tags:[...o.tags.filter(t=>t.id!==tag.id),tag]}));setValue(v=>({...v,tags:Array.from(new Set([...v.tags,tag.id]))}))}}/><p className="muted">Existing artists keep their profiles and other albums. Requested tracks remain missing until they are matched in Plex.</p></details></>}
 </>}
 </div><div className="modal-footer"><button disabled={saving} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||saving||!selected} onClick={add}>{saving?'Queuing…':'Add to Lidarr'}</button></div></div></Modal>
}
