import { useEffect, useRef, useState } from 'react'
import Modal from './Modal'
import { showActivity } from './Activity'
import { MissingTrack } from './api'

type Defaults={root_folder:string;quality_profile_id:number;metadata_profile_id:number;monitor:string;monitor_new:string;monitor_album:boolean;search_now:boolean;tags:number[];tag_existing:boolean}
type Settings=Defaults&{enabled:boolean;url:string;api_key:string;api_key_saved?:boolean;musicbrainz_enabled:boolean;cache_days:number;cache_entries?:number}
type Root={id:number;path:string;defaultQualityProfileId?:number;defaultMetadataProfileId?:number;defaultMonitorOption?:string;defaultNewItemMonitorOption?:string;defaultTags?:number[]}
type Options={version:string;roots:Root[];tags:{id:number;label:string}[];qualities:{id:number;name:string}[];metadata:{id:number;name:string}[]}
type Album={album_id:string;title:string;artist:string;year:string;type:string;secondary_types:string[];exists:boolean|null}
type Preview={preview_id:string;album:Album;artist_exists:boolean;album_exists:boolean;album_monitored:boolean;defaults:Defaults;quality:string;metadata:string;tags:string[]}
const monitorLabels:Record<string,string>={selected:'Only the selected album',all:'All albums',future:'Future albums',missing:'Missing albums',existing:'Albums with files',none:'None'}
const defaults:Settings={enabled:false,url:'',api_key:'',root_folder:'',quality_profile_id:0,metadata_profile_id:0,monitor:'selected',monitor_new:'none',monitor_album:true,search_now:false,musicbrainz_enabled:true,cache_days:7,tags:[],tag_existing:false}
const noOptions:Options={version:'',roots:[],qualities:[],metadata:[],tags:[]}
async function call<T>(path:string,method='GET',body?:unknown):Promise<T>{
 const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),180000)
 try{const response=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(typeof data.detail==='string'?data.detail:'Check the selected settings and try again.');return data}
 catch(e:any){if(e.name==='AbortError')throw new Error('Lidarr request timed out. Check its connection before retrying.');throw e}finally{clearTimeout(timer)}
}
function rootDefaults(value:Defaults,root:Root):Defaults{
 const monitor=root.defaultMonitorOption&&monitorLabels[root.defaultMonitorOption]?root.defaultMonitorOption:value.monitor
 return {...value,root_folder:root.path,quality_profile_id:root.defaultQualityProfileId??value.quality_profile_id,metadata_profile_id:root.defaultMetadataProfileId??value.metadata_profile_id,monitor,monitor_new:root.defaultNewItemMonitorOption||value.monitor_new,monitor_album:monitor!=='none',search_now:monitor==='none'?false:value.search_now,tags:root.defaultTags||[]}
}
function DefaultFields({value,options,onChange,disabled=false}:{value:Defaults;options:Options;onChange:(v:Defaults)=>void;disabled?:boolean}){
 const set=(key:string,v:unknown)=>onChange({...value,[key]:v})
 return <fieldset disabled={disabled} className="lidarr-fields"><div className="form-grid">
 <label>Root folder<select value={value.root_folder} onChange={e=>{const root=options.roots.find(r=>r.path===e.target.value);onChange(root?rootDefaults(value,root):{...value,root_folder:''})}}><option value="">Select root folder</option>{options.roots.map(r=><option key={r.id} value={r.path}>{r.path}</option>)}</select></label>
 <label>Quality profile<select value={value.quality_profile_id} onChange={e=>set('quality_profile_id',Number(e.target.value))}><option value={0}>Select quality profile</option>{options.qualities.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>Metadata profile<select value={value.metadata_profile_id} onChange={e=>set('metadata_profile_id',Number(e.target.value))}><option value={0}>Select metadata profile</option>{options.metadata.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select></label>
 <label>Albums to monitor for new artists<select value={value.monitor} onChange={e=>onChange({...value,monitor:e.target.value,...(e.target.value==='none'?{monitor_album:false,search_now:false}:e.target.value==='selected'?{monitor_album:true}:{})})}>{Object.entries(monitorLabels).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>
 <label>New releases discovered later<select value={value.monitor_new} onChange={e=>set('monitor_new',e.target.value)}><option value="none">Do not monitor</option><option value="new">New releases only</option><option value="all">All newly discovered albums</option></select></label>
 <label>Artist tags<select multiple aria-label="Lidarr tags" value={value.tags.map(String)} onChange={e=>set('tags',Array.from(e.target.selectedOptions,o=>Number(o.value)))}>{options.tags.map(t=><option key={t.id} value={t.id}>{t.label}</option>)}</select></label>
 </div><button type="button" disabled={!options.roots.find(r=>r.path===value.root_folder)?.defaultMetadataProfileId} onClick={()=>{const root=options.roots.find(r=>r.path===value.root_folder);if(root)onChange(rootDefaults(value,root))}}>Use Root Folder Defaults</button><p className="muted">Choosing a root folder loads its defaults. A metadata profile named None is valid and separate from monitoring None.</p><label className="playlist-choice"><input type="checkbox" checked={value.monitor_album} onChange={e=>onChange({...value,monitor_album:e.target.checked,...(!e.target.checked?{search_now:false,...(value.monitor==='selected'?{monitor:'none'}:{})}:value.monitor==='none'?{monitor:'selected'}:{})})}/> Monitor the selected album</label>
 <label className="playlist-choice"><input type="checkbox" checked={value.search_now} disabled={!value.monitor_album} onChange={e=>set('search_now',e.target.checked)}/> Search immediately for the selected album</label>
 <label className="playlist-choice"><input type="checkbox" checked={value.tag_existing} onChange={e=>set('tag_existing',e.target.checked)}/> Also add selected tags to existing artists (keep their other tags)</label>
 </fieldset>
}
export default function LidarrSettings(){
 const [value,setValue]=useState<Settings>(defaults),[options,setOptions]=useState<Options>(noOptions),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[tagLabel,setTagLabel]=useState('')
 useEffect(()=>{let active=true;call<Settings>('/api/settings/lidarr').then(s=>{if(active){setValue({...defaults,...s,api_key:''});setLoaded(true)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[])
 async function discover(){setBusy(true);setError('');setMessage('Connecting to Lidarr and loading profiles…');try{const result=await call<Options>('/api/settings/lidarr/test','POST',value);setOptions(result);setMessage(`Connected to Lidarr ${result.version}. Root folders and profiles loaded.`)}catch(e:any){setError(e.message);setMessage('')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');setMessage('Saving settings…');try{const result=await call<Settings>('/api/settings/lidarr','PUT',value);setValue({...defaults,...result,api_key:'',cache_entries:value.cache_entries});setMessage('Lidarr settings saved.')}catch(e:any){setError(e.message);setMessage('')}finally{setBusy(false)}}
 const displayOptions={...options,roots:options.roots.length?options.roots:value.root_folder?[{id:-1,path:value.root_folder}]:[],qualities:options.qualities.length?options.qualities:value.quality_profile_id?[{id:value.quality_profile_id,name:`Saved profile (${value.quality_profile_id}) — connect to load names`}]:[],metadata:options.metadata.length?options.metadata:value.metadata_profile_id?[{id:value.metadata_profile_id,name:`Saved profile (${value.metadata_profile_id}) — connect to load names`}]:[]}
 return <section className="panel settings-panel"><h2>Lidarr</h2><p className="muted">Add albums from Missing after reviewing each selection.</p>{!loaded&&!error&&<p>Loading settings…</p>}
 <fieldset disabled={!loaded||busy} className="lidarr-fields"><label className="playlist-choice"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/> Enable Lidarr integration</label><div className="form-grid">
 <label>Lidarr URL<input value={value.url} placeholder="http://lidarr:8686" onChange={e=>{setValue({...value,url:e.target.value});setOptions(noOptions)}}/></label>
 <label>API key<input type="password" autoComplete="new-password" value={value.api_key} placeholder={value.api_key_saved?'Saved — leave blank to keep':'Enter Lidarr API key'} onChange={e=>setValue({...value,api_key:e.target.value})}/></label></div><button type="button" onClick={discover} disabled={!value.url}>Test Connection & Load Profiles</button>
 <h3>Album defaults</h3><DefaultFields value={value} options={displayOptions} onChange={v=>setValue({...value,...v})}/><p className="muted">Root folder, profiles and artist-wide monitoring apply to new artists. Existing artists keep their Lidarr settings; existing monitored albums stay monitored.</p>
 <h3>Create an artist tag</h3><div className="add"><input aria-label="New Lidarr tag" placeholder="playlist-bridge" value={tagLabel} onChange={e=>setTagLabel(e.target.value.toLowerCase())}/><button type="button" disabled={!/^[a-z0-9-]+$/.test(tagLabel)} onClick={async()=>{setBusy(true);setError('');try{const tag=await call<{id:number;label:string}>('/api/settings/lidarr/tag','POST',{...value,label:tagLabel});setOptions(o=>({...o,tags:[...o.tags.filter(t=>t.id!==tag.id),tag]}));setValue(v=>({...v,tags:Array.from(new Set([...v.tags,tag.id]))}));setTagLabel('');setMessage('Tag is available in Lidarr and selected here. Save Changes to use it as a default.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Create Tag in Lidarr</button></div>
 <h3>MusicBrainz</h3><label className="playlist-choice"><input type="checkbox" checked={value.musicbrainz_enabled} onChange={e=>setValue({...value,musicbrainz_enabled:e.target.checked})}/> Use MusicBrainz to find albums for missing tracks</label><p className="muted">No account or API key is needed. Lookups run only when requested, with local caching and a limit of one request per second.</p>
 <label>Keep metadata results for <select value={value.cache_days} onChange={e=>setValue({...value,cache_days:Number(e.target.value)})}><option value={7}>7 days</option><option value={30}>30 days</option></select></label><p className="muted">{value.cache_entries||0} cached lookups · up to 500 retained</p>
 <button type="button" onClick={async()=>{setBusy(true);setError('');try{await call('/api/settings/lidarr/cache','DELETE');setValue(v=>({...v,cache_entries:0}));setMessage('Metadata cache cleared.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Clear Metadata Cache</button>
 <div className="settings-save"><button className="primary" type="button" onClick={save}>Save Changes</button></div></fieldset>
 {message&&<p role="status">{message}</p>}{error&&<p role="alert" className="error">{error}</p>}</section>
}
export function AddLidarrAlbum({track,onClose}:{track:Pick<MissingTrack,'title'|'artist'|'album'>;onClose:()=>void}){
 const [settings,setSettings]=useState<Settings|null>(null),[options,setOptions]=useState<Options>(noOptions),[value,setValue]=useState<Defaults>(defaults)
 const [query,setQuery]=useState(track.album&&track.album!=='N/A'?track.album:''),[rows,setRows]=useState<Album[]>([]),[selected,setSelected]=useState<Album|null>(null),[preview,setPreview]=useState<Preview|null>(null),[message,setMessage]=useState('Loading Lidarr settings…'),[error,setError]=useState(''),[busy,setBusy]=useState(true),[saving,setSaving]=useState(false)
 const generation=useRef(0)
 useEffect(()=>{const g=++generation.current;(async()=>{try{const s=await call<Settings>('/api/settings/lidarr');if(g!==generation.current)return;setSettings({...s,api_key:''});setValue(s);if(s.enabled){const o=await call<Options>('/api/settings/lidarr/test','POST',{...s,api_key:''});if(g!==generation.current)return;setOptions(o);setMessage('Search by album name, or find possible albums for this source track.')}else setMessage('Configure and enable Lidarr first.')}catch(e:any){if(g===generation.current)setError(e.message)}finally{if(g===generation.current)setBusy(false)}})();return()=>{generation.current++}},[])
 async function search(provider:string){const g=++generation.current;setBusy(true);setError('');setSelected(null);setPreview(null);setRows([]);setMessage(provider==='musicbrainz'?'Finding album candidates with MusicBrainz…':'Searching Lidarr…');try{const result=await call<{rows:Album[];provider:string;cached:boolean}>('/api/lidarr/search','POST',{...track,query,provider});if(g!==generation.current)return;setRows(result.rows);setMessage(`${result.rows.length} album candidates · ${result.provider}${result.cached?' · cached':''}. Review the album and recording version before adding.`)}catch(e:any){if(g===generation.current){setError(e.message);setMessage('')}}finally{if(g===generation.current)setBusy(false)}}
 async function review(){if(!selected)return;const g=++generation.current;setBusy(true);setError('');setMessage('Checking album identity and existing Lidarr entries…');try{const p=await call<Preview>('/api/lidarr/preview','POST',{...value,album_id:selected.album_id});if(g===generation.current){setPreview(p);setMessage('Review this selection before confirming.')}}catch(e:any){if(g===generation.current){setError(e.message);setMessage('')}}finally{if(g===generation.current)setBusy(false)}}
 async function confirm(){if(!preview||saving)return;setSaving(true);setError('');try{const job=await call<{id:string}>('/api/lidarr/add','POST',{preview_id:preview.preview_id});onClose();showActivity(job.id)}catch(e:any){setError(e.message)}finally{setSaving(false)}}
 return <Modal onClose={onClose} busy={saving}><div className="modal match-dialog" role="dialog" aria-modal="true" aria-labelledby="lidarr-album-title"><div className="modal-header"><h2 id="lidarr-album-title">Add Album to Lidarr</h2><button disabled={saving} onClick={onClose} aria-label="Close Lidarr album review">✕</button></div><div className="modal-body"><h3>{track.title} — {track.artist}</h3>{message&&<p role="status">{busy&&<span className="spinner"/>}{message}</p>}{error&&<p className="error" role="alert">{error}</p>}
 {settings&&!settings.enabled?<p><a href="#settings/lidarr" onClick={onClose}>Open Lidarr settings</a></p>:settings&&<>
 {!preview?<><form className="add" onSubmit={e=>{e.preventDefault();search('lidarr')}}><input aria-label="Search Lidarr albums" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Album name or lidarr:MusicBrainz-ID"/><button disabled={busy||!query.trim()}>Search Albums</button></form><button disabled={busy||!settings.musicbrainz_enabled} onClick={()=>search('musicbrainz')}>Find Albums for This Track</button>
 <div className="lidarr-candidates">{rows.map(a=><button disabled={busy} className={`candidate ${selected?.album_id===a.album_id?'chosen':''}`} aria-pressed={selected?.album_id===a.album_id} key={a.album_id} onClick={()=>setSelected(a)}><span><strong>{a.title}</strong><small>{a.artist} · {a.year||'Year unknown'} · {[a.type,...a.secondary_types].filter(Boolean).join(', ')}</small>{a.exists&&<small>Already in Lidarr</small>}</span></button>)}</div>
 {selected&&<><h3>Options for this album</h3><DefaultFields value={value} options={options} onChange={setValue} disabled={busy}/><p className="muted">New-artist defaults apply only if this artist is not already in Lidarr. Existing artist settings and other albums are preserved.</p></>}
 </>:<div className="lidarr-review"><h3>{preview.album.title}</h3><p>{preview.album.artist} · {preview.album.year} · {[preview.album.type,...preview.album.secondary_types].filter(Boolean).join(', ')}</p><p>{preview.album_exists?'Album is already in Lidarr.':'Album will be added to Lidarr.'} {preview.artist_exists?'The existing artist’s profiles and other albums stay unchanged.':'The artist will also be added.'}</p>
 {!preview.artist_exists&&<><p>Root folder: {preview.defaults.root_folder}</p><p>Quality: {preview.quality} · Metadata: {preview.metadata}</p><p>Tags: {preview.tags.join(", ")||"None"}</p><p>Artist monitoring: {monitorLabels[preview.defaults.monitor]} · Future discoveries: {{none:'Do not monitor',new:'New releases only',all:'All newly discovered albums'}[preview.defaults.monitor_new]||preview.defaults.monitor_new}</p></>}
 <p>{preview.artist_exists&&preview.defaults.tag_existing?`Add artist tags: ${preview.tags.join(", ")||"None"}; existing tags will be kept.`:""}</p><p>Selected album: {preview.album_monitored?'already monitored; stays monitored':preview.defaults.monitor_album?'will be monitored':'will not be monitored'}</p><p>{preview.defaults.search_now?'Search immediately for this album.':'Do not start a search now.'}</p><p className="muted">Adding to Lidarr does not resolve this track in Bridge. After the music arrives in Plex, run Sync / Refresh.</p><button disabled={saving} onClick={()=>{setPreview(null);setMessage('Adjust options or select another album.')}}>Back to Options</button></div>}
 </>}
 </div><div className="modal-footer"><button disabled={saving} onClick={onClose}>Cancel</button>{preview?<button className="primary" disabled={saving} onClick={confirm}>{saving?'Queuing…':preview.album_exists?'Confirm Album Options':'Confirm Add Album'}</button>:<button className="primary" disabled={busy||!selected} onClick={review}>Review Album</button>}</div></div></Modal>
}
