import {useEffect,useState} from 'react'
import {request} from './api'
import ErrorNotice from './ErrorNotice'
import Modal from './Modal'
import {FilterMenu,SortMenu,FilterChips,filterMatches,Icon} from './Controls'

function jobNotice(job:any){window.dispatchEvent(new CustomEvent('jobs-refresh'));return `Queued. Follow progress in Activity (${job.id.slice(0,8)}).`}
export function LocalLibrarySettings(){
 const [value,setValue]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{request('/api/settings/local-library').then(setValue).catch(e=>setError(e.message))},[])
 async function save(){setBusy(true);setError('');try{setValue(await request('/api/settings/local-library',{method:'PUT',body:JSON.stringify(value)}));setMessage('Saved. Run a local scan to update the library.')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel settings-panel"><h2>Local Music Library</h2><p>Scan audio files and reconcile MusicBrainz identities. Scanning is read-only: no tags, folders, or files are changed.</p>{error&&<ErrorNotice error={error}/ >}{!value&&!error&&<p>Loading settings…</p>}{value&&<fieldset disabled={busy} className="lidarr-fields"><label className="playlist-choice"><input type="checkbox" checked={value.enabled} onChange={e=>setValue({...value,enabled:e.target.checked})}/>Use local files for Library</label><p>Mount your music folder into the container as read-only, for example <code>/music</code>. Enter the container path below. If Plex sees the same files at another path, supply that path too.</p>{value.roots.map((r:any,i:number)=><div className="form-grid" key={i}><label>Music folder<input value={r.path} placeholder="/music" onChange={e=>setValue({...value,roots:value.roots.map((v:any,n:number)=>n===i?{...v,path:e.target.value}:v)})}/></label><label>Same folder in Plex (optional)<input value={r.plex_path} placeholder="/data/media/music" onChange={e=>setValue({...value,roots:value.roots.map((v:any,n:number)=>n===i?{...v,plex_path:e.target.value}:v)})}/></label><button onClick={()=>setValue({...value,roots:value.roots.filter((_:any,n:number)=>i!==n)})}>Remove Folder</button></div>)}<div className="actions"><button onClick={()=>setValue({...value,roots:[...value.roots,{path:'',plex_path:''}]})}>Add Music Folder</button><button className="primary" onClick={save}>Save Changes</button></div><p><a href="#settings/musicbrainz">MusicBrainz release preferences →</a> · <a href="#settings/tasks">Schedule scans in Tasks →</a></p></fieldset>}{message&&<p role="status">{message}</p>}</section>
}

export default function LocalLibrary(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[artist,setArtist]=useState(''),[selected,setSelected]=useState(''),[attention,setAttention]=useState(false),[filters,setFilters]=useState<string[]>([]),[types,setTypes]=useState<string[]>([]),[sort,setSort]=useState('year:asc'),[modal,setModal]=useState<any>(null),[id,setId]=useState(''),[editions,setEditions]=useState<any[]>([]),[busy,setBusy]=useState(false)
 async function load(){try{setData(await request('/api/library/local'));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[])
 async function queue(path:string,body:any={}){setBusy(true);setError('');try{const j=await request(path,{method:'POST',body:JSON.stringify(body)});setMessage(jobNotice(j))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const album=data?.rows.find((r:any)=>r.album_id===selected)
 const rows=(data?.rows||[]).filter((r:any)=>(!artist||r.artist===artist)&&`${r.artist} ${r.title}`.toLowerCase().includes(query.toLowerCase())&&filterMatches(filters,f=>r.status===f)&&filterMatches(types,f=>r.type===f||r.secondary_types.includes(f))).sort((a:any,b:any)=>String(a[sort.split(':')[0]]||'').localeCompare(String(b[sort.split(':')[0]]||''))*(sort.endsWith('desc')?-1:1))
 const artists=[...new Set<string>((data?.rows||[]).map((r:any)=>r.artist))]
 async function releaseOptions(){setBusy(true);setError('');try{const result=await request<any>('/api/library/local/releases/'+album.album_id);setEditions(result.rows);setModal({kind:'editions'})}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function saveFolder(folder:string){setBusy(true);setError('');try{await request('/api/library/local/folders/'+folder+'/link',{method:'PUT',body:JSON.stringify({release_id:id.trim()})});setModal(null);setMessage('Association saved; file tags remain unchanged.');setSelected('');await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><section className="panel"><div className="panel-head"><div><h2>{album?.title||artist||'Music Library'}</h2><p className="muted">Local files · MusicBrainz catalog · Plex playback</p></div><div className="actions"><button onClick={()=>{setAttention(!attention);setSelected('')}}>Needs Attention · {data?.errors.length||0}</button><button onClick={load} aria-label="Refresh library"><Icon name="refresh"/></button></div></div><div className="actions">{(artist||selected)&&<button onClick={()=>selected?setSelected(''):setArtist('')}>← Back</button>}<button disabled={busy} onClick={()=>queue('/api/library/local/scan')}>Scan Local Files</button><button onClick={()=>{setModal({kind:'artist'});setId('')}}>Add Artist Catalog</button><a href="#settings/local-library">Library Settings</a></div>{message&&<p role="status">{message} <a href="#activity">View Activity</a></p>}{error&&<ErrorNotice error={error}/ >}{!data&&<p>Loading library…</p>}{data&&!data.checked_at&&<p>Run your first local scan. Lidarr remains available until you enable local scanning in Library Settings.</p>}{data?.checked_at&&<small>Local files checked {new Date(data.checked_at*1000).toLocaleString()}</small>}{!album&&!attention&&<><input aria-label="Filter library" placeholder="Filter artists or albums" value={query} onChange={e=>setQuery(e.target.value)}/><div className="actions"><label>Artist<select value={artist} onChange={e=>setArtist(e.target.value)}><option value="">All artists</option>{artists.map(a=><option key={a}>{a}</option>)}</select></label><FilterMenu choices={['Album','EP','Single','Live','Compilation','Remix','Soundtrack']} value={types} onChange={setTypes}/><FilterMenu choices={['Available','Partial','Missing','Needs Attention','Awaiting Plex','Plex scan pending']} value={filters} onChange={setFilters}/><SortMenu choices={{'year:asc':'Release date','title:asc':'Album','artist:asc':'Artist'}} value={sort} onChange={setSort}/></div><FilterChips value={types} onChange={setTypes}/><FilterChips value={filters} onChange={setFilters}/></>}</section>
 {attention?<section className="panel">{data?.errors.map((r:any)=><article className="missing-row" key={r.id}><div><strong>{r.title}</strong><small>{r.artist}</small><p>{r.reason}</p></div>{r.album_id&&<button onClick={()=>{setSelected(r.album_id);setAttention(false)}}>Review</button>}</article>)}{data&&!data.errors.length&&<p>No issues in the current local inventory.</p>}</section>:album?<section className="panel"><h3>{album.artist} · {album.year||'Year unknown'}</h3><p>{album.status} · {album.local_count} local files · {album.plex_count} linked to Plex{album.expected_tracks?` · ${album.expected_tracks} tracks on selected edition`:''}</p><p>{album.reason}</p><div className="actions">{!album.album_id.startsWith('unidentified:')&&<><a href={'https://musicbrainz.org/release-group/'+album.album_id} target="_blank" rel="noreferrer">MusicBrainz ↗</a><button disabled={busy} onClick={releaseOptions}>Review Editions</button></>}{album.artist_id&&<button disabled={busy} onClick={()=>queue('/api/library/local/catalog',{artist_id:album.artist_id})}>Refresh Artist Catalog</button>}{[...new Set<string>(album.tracks.map((t:any)=>t.folder_id))].map(folder=><button key={folder} onClick={()=>{setModal({kind:'folder',folder});setId('')}}>Link MusicBrainz Edition</button>)}{album.release_ids.map((rid:string)=><button key={rid} disabled={busy} onClick={()=>queue('/api/library/local/catalog',{release_id:rid})}>Load Edition Metadata · {rid.slice(0,8)}</button>)}</div>{album.tracks.map((t:any)=><article className="missing-row" key={t.id}><div className="grow"><strong>{t.track_number}. {t.title}</strong><small>{t.format} · {t.bitrate?Math.round(t.bitrate/1000)+' kbps':'Bitrate unknown'} · {t.link?'Linked to Plex':'Not confirmed in Plex'}</small><small>{t.file}</small></div><button onClick={()=>{setModal({kind:'track',track:t});setId('')}}>Review Recording</button></article>)}</section>:<div className="discover-grid">{rows.map((r:any)=><button className="panel album-card" key={r.album_id} onClick={()=>setSelected(r.album_id)}>{r.album_id.startsWith('unidentified:')?<div className="album-art-placeholder">♫</div>:<img src={'https://coverartarchive.org/release-group/'+r.album_id+'/front-250'} alt="" loading="lazy" onError={e=>{e.currentTarget.style.visibility='hidden'}}/>}<h3>{r.title}</h3><p>{r.artist} · {r.year||'Year unknown'}</p><p>{r.status}{r.local_count>0?` · ${r.local_count} files`:''}</p></button>)}{data&&!rows.length&&<p>No albums match. Scan local files or add a MusicBrainz artist catalog.</p>}</div>}
 {modal&&<Modal onClose={()=>setModal(null)} busy={busy}><section className="modal" role="dialog" aria-modal="true" aria-label="MusicBrainz association"><div className="modal-header"><h2>{modal.kind==='artist'?'Add Artist Catalog':modal.kind==='editions'?'Release Editions':modal.kind==='track'?'Review Recording':'Link Album Edition'}</h2><button disabled={busy} onClick={()=>setModal(null)}>Close</button></div><div className="modal-body">{error&&<ErrorNotice error={error}/ >}{modal.kind==='editions'?<><p><button disabled={busy} onClick={()=>queue('/api/library/local/catalog',{group_id:album.album_id})}>Refresh Edition List</button> Ordered by your <a href="#settings/musicbrainz">release preferences</a>. Loading metadata does not replace your files or choose an edition automatically.</p>{!editions.length&&<p>Refresh the edition list, then reopen this panel when the job completes.</p>}{editions.map(r=><div className="album-result" key={r.id}><div className="grow"><strong>{r.title}</strong><p>{r.date||'Date unknown'} · {r.country||'Country unknown'} · {r.media?.map((m:any)=>m.format).join(', ')} · {r.status}</p></div><a href={'https://musicbrainz.org/release/'+r.id} target="_blank" rel="noreferrer">Review ↗</a><button disabled={busy} onClick={()=>{setId(r.id);void queue('/api/library/local/catalog',{release_id:r.id})}}>Load Metadata</button></div>)}</>:modal.kind==='track'?<TrackAssociation track={modal.track} onSaved={()=>{setModal(null);void load()}}/>:<><p>{modal.kind==='artist'?'Enter a MusicBrainz artist ID to load their discography into this unified library.':'Enter a MusicBrainz release ID. Load its metadata first, then save the folder association. File tags are never changed.'}</p><label>MusicBrainz ID<input value={id} onChange={e=>setId(e.target.value)} placeholder="xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"/></label><div className="actions"><button disabled={busy||!id.trim()} onClick={()=>queue('/api/library/local/catalog',modal.kind==='artist'?{artist_id:id.trim()}:{release_id:id.trim()})}>Load Metadata</button>{modal.kind==='folder'&&<button disabled={busy||!id.trim()} onClick={()=>saveFolder(modal.folder)}>Save Association</button>}</div>{message&&<p>{message}</p>}</>}</div></section></Modal>}</>
}
function TrackAssociation({track,onSaved}:{track:any;onSaved:()=>void}){
 const [id,setId]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const options=(track.selected_release?.media||[]).flatMap((m:any)=>(m.tracks||[]).map((t:any)=>({...t,disc:m.position})))
 async function save(){setBusy(true);try{await request('/api/library/local/tracks/'+track.id+'/link',{method:'PUT',body:JSON.stringify({release_id:track.selected_release_id,release_track_id:id})});onSaved()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><p>{track.title} · {track.album}</p><p>Confirm the exact recording on the selected edition. This changes Bridge’s association only.</p>{error&&<ErrorNotice error={error}/ >}<select aria-label="Release track" value={id} onChange={e=>setId(e.target.value)}><option value="">Choose a track</option>{options.map((t:any)=><option key={t.id} value={t.id}>{t.disc}.{t.position} · {t.title||t.recording?.title}</option>)}</select>{!options.length&&<p>Link an edition and load its metadata first.</p>}<button disabled={busy||!id} onClick={save}>Confirm Association</button></>
}
