import ErrorNotice from './ErrorNotice'
import { useEffect, useState } from 'react'
import { api, Job, Playlist } from './api'
import Modal from './Modal'
import { playlistPredicates, FILTER_STORAGE, normalizePlaylistFilters } from './playlistFilters'
import HealthCard, { RelativeTime, HealthIndicator } from './HealthCard'

import { filterMatches, Icon, FilterMenu, FilterChips, SortMenu } from './Controls'

const savedView=(initial?:string)=>{try{const value=initial?JSON.parse(decodeURIComponent(initial)):JSON.parse(localStorage.getItem(FILTER_STORAGE)||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
const filterChoices=Object.keys(playlistPredicates)
const link=(key:string)=>`#playlist/${encodeURIComponent(key)}`
export default function PlaylistsView({playlists,loaded,enqueue,refresh,initialView}:{initialView?:string;playlists:Playlist[];loaded:boolean;enqueue:(action:string,payload?:any)=>Promise<Job>;refresh:()=>Promise<void>}){
 const [query,setQuery]=useState<string>(()=>typeof savedView(initialView).query==='string'?savedView(initialView).query:''),[filters,setFilters]=useState<string[]>(()=>Array.isArray(savedView(initialView).filters)?normalizePlaylistFilters(savedView(initialView).filters):[]),[sort,setSort]=useState(()=>(()=>{const s=savedView(initialView).sort;return ['name:asc','name:desc','last_synced:asc','last_synced:desc','unresolved:asc','unresolved:desc'].includes(s)?s:s==='last_synced'?'last_synced:desc':'name:asc'})()),[error,setError]=useState(''),[remove,setRemove]=useState<Playlist[]>([]),[removing,setRemoving]=useState(false)
 const [selected,setSelected]=useState<string[]>([]),[deletePlex,setDeletePlex]=useState(false)
 const [view,setView]=useState(()=>{try{return localStorage.getItem('playlist-bridge-view')==='compact'?'compact':'expanded'}catch{return 'expanded'}})
 const predicates=playlistPredicates
 const rows=playlists.filter(p=>filterMatches(filters,f=>!!predicates[f]?.(p),'all')&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>(()=>{const [field,dir]=sort.split(':');const x=field==='name'?a.name:field==='unresolved'?a.unresolved:a.last_synced?Date.parse(a.last_synced):null,y=field==='name'?b.name:field==='unresolved'?b.unresolved:b.last_synced?Date.parse(b.last_synced):null;if(x===null)return y===null?0:1;if(y===null)return -1;return (typeof x==='string'?x.localeCompare(String(y),undefined,{numeric:true,sensitivity:'base'}):x-Number(y))*(dir==='desc'?-1:1)||a.name.localeCompare(b.name)})())
 useEffect(()=>{setSelected(current=>current.filter(key=>rows.some(p=>p.key===key)))},[query,filters,playlists])
 useEffect(()=>{try{localStorage.setItem('bridge-playlist-filters',JSON.stringify({query,filters,sort}))}catch{}},[query,filters,sort])
 useEffect(()=>{if(initialView)history.replaceState(null,'','#playlists')},[])
 const actionKeys=selected.length?selected:rows.map(p=>p.key)
 function askRemove(items:Playlist[]){setDeletePlex(false);setRemove(items)}
 async function run(fn:()=>Promise<any>){try{setError('');const result=await fn();if(result?.queued){window.dispatchEvent(new CustomEvent('bridge-notice',{detail:result.message}));window.dispatchEvent(new Event('jobs-refresh'))}await refresh()}catch(e:any){setError(e.message)}}
 function toggleView(){const next=view==='compact'?'expanded':'compact';setView(next);try{localStorage.setItem('playlist-bridge-view',next)}catch{}}
 function clear(){setFilters([]);setQuery('')}
 return <section className="panel playlist-list"><div className="list-controls"><h2>Your playlists</h2><div className="actions toolbar-icons"><FilterMenu choices={Object.keys(predicates)} value={filters} onChange={setFilters}/><SortMenu choices={{'name:asc':'Name: ascending (A–Z)','name:desc':'Name: descending (Z–A)','last_synced:asc':'Last synced: oldest first','last_synced:desc':'Last synced: newest first','unresolved:asc':'Missing tracks: fewest first','unresolved:desc':'Missing tracks: most first'}} value={sort} onChange={setSort}/><button className="icon-button" aria-label="Refresh playlist list" title="Refresh" onClick={()=>{void refresh().catch(e=>setError(e.message))}}><Icon name="refresh"/></button><button className="icon-button" title={`Switch to ${view==='compact'?'expanded':'compact'}`} aria-label={`Switch to ${view==='compact'?'expanded':'compact'} view`} onClick={toggleView}><Icon name={view}/></button><button className="primary" disabled={!loaded||!rows.length} onClick={()=>run(()=>enqueue('sync',{scope:'selected',playlist_keys:actionKeys}))}>{selected.length?'Sync Selected':'Sync Filtered'} ({actionKeys.length})</button></div></div>
 <div className="toolbar list-secondary"><input aria-label="Filter playlists by name" placeholder="Filter by playlist name" value={query} onChange={e=>setQuery(e.target.value)}/></div><FilterChips value={filters} onChange={setFilters}/>
 {loaded&&<p className="muted list-count">{rows.length} of {playlists.length} playlists{filters.length?' · all selected filters apply':''}</p>}{error&&<ErrorNotice error={error}/>}
 {loaded&&!!rows.length&&<div className="selection-bar"><label><input type="checkbox" aria-label="Select all visible playlists" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(p=>p.key):[])}/> Select visible</label>{!!selected.length&&<><span>{selected.length} selected</span><button className="small-button danger-action" onClick={()=>askRemove(rows.filter(p=>selected.includes(p.key)))}>Remove selected</button><button className="small-button" onClick={()=>setSelected([])}>Clear selection</button></>}</div>}
 {rows.map(p=><article className={`playlist-item ${view}`} key={p.key}><div className="playlist-main"><input type="checkbox" aria-label={`Select ${p.name}`} checked={selected.includes(p.key)} onChange={e=>setSelected(e.target.checked?[...selected,p.key]:selected.filter(k=>k!==p.key))}/><div className="playlist-identity"><a className="playlist-name" href={link(p.key)}>{p.name}</a><p className="muted">{p.source==='spotify'?'Spotify':'Apple Music'} · {p.health?.source_tracks??p.saved_matches} tracks · <RelativeTime value={p.last_synced} prefix="Synced"/></p></div><a className="small-button" href={link(p.key)} title={`${p.schedule?.mode==='custom'?'Custom schedule':p.schedule?.mode==='disabled'?'Manual only':'Server schedule'}${p.schedule?.next_run?' · Next: '+new Date(p.schedule.next_run).toLocaleString():''}`} aria-label={`Sync mode for ${p.name}`}><Icon name="autosync"/><span>{p.schedule?.mode==='custom'?'Custom':p.schedule?.mode==='disabled'?'Manual':'Server'}</span></a>{p.settings_pending&&<span className="pill">Change queued</span>}{p.ready_to_sync&&<span className="pill">Ready to Sync</span>}<HealthIndicator playlist={p}/><button className="small-button" onClick={()=>run(()=>enqueue('sync',{scope:'selected',playlist_keys:[p.key]}))}>Sync Now</button><details className="playlist-menu"><summary aria-label={`More actions for ${p.name}`} title="More actions">⋯</summary><div className="row-menu"><button className="danger-action" onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');askRemove([p])}}>Remove Playlist</button></div></details></div>
 {view==='expanded'&&<div className="playlist-expanded"><p className="muted">{p.saved_matches} stored mappings · {p.match_counts?.automatic||0} Auto · {p.match_counts?.manual||0} Manual · {p.match_counts?.legacy||0} Saved · {p.unresolved} missing · {p.lost} LOST</p><HealthCard playlist={p}/></div>}</article>)}
 {!loaded?<p role="status">Loading playlists…</p>:!rows.length&&<div className="empty-state"><h3>{playlists.length?'No playlists match your filters':'No playlists yet'}</h3>{playlists.length?<button onClick={clear}>Clear Filters</button>:<a className="button-link" href="#dashboard/add">Add Playlist</a>}</div>}
 {!!remove.length&&<Modal onClose={()=>setRemove([])} busy={removing}><div className="modal" role="dialog" aria-modal="true" aria-label="Remove playlists"><h2>Remove {remove.length} playlist{remove.length===1?'':'s'}?</h2><ul>{remove.map(p=><li key={p.key}>{p.name}</li>)}</ul><label className="playlist-choice"><input type="radio" name="remove-mode" checked={!deletePlex} onChange={()=>setDeletePlex(false)}/> Remove from Bridge only — leave Plex playlists untouched</label><label className="playlist-choice"><input type="radio" name="remove-mode" checked={deletePlex} onChange={()=>setDeletePlex(true)}/> Also delete these playlists from Plex</label><p>{deletePlex?'The selected Plex playlists will be deleted. Music files in your library are not deleted.':'Plex playlists will remain unchanged.'} Historical job output is retained.</p>{error&&<ErrorNotice error={error}/>}<div className="actions"><button disabled={removing} onClick={()=>setRemove([])}>Cancel</button><button disabled={removing} className={deletePlex?'danger-action':''} onClick={async()=>{setRemoving(true);try{await enqueue('remove',{playlist_keys:remove.map(p=>p.key),delete_plex:deletePlex});setRemove([]);setSelected([])}catch(e:any){setError(e.message)}finally{setRemoving(false)}}}>{deletePlex?'Delete from Bridge and Plex':'Remove from Bridge only'}</button></div></div></Modal>}

 </section>
}
