import { useEffect, useState } from 'react'
import { api, Job, Playlist } from './api'
import Modal from './Modal'
import { playlistPredicates, FILTER_STORAGE } from './playlistFilters'
import HealthCard, { RelativeTime, HealthIndicator } from './HealthCard'

import { Icon, FilterMenu, FilterChips, SortMenu } from './Controls'

const savedView=(initial?:string)=>{try{const value=initial?JSON.parse(decodeURIComponent(initial)):JSON.parse(localStorage.getItem(FILTER_STORAGE)||'{}');return value&&typeof value==='object'?value:{}}catch{return {}}}
const filterChoices=Object.keys(playlistPredicates)
const link=(key:string)=>`#playlist/${encodeURIComponent(key)}`
export default function PlaylistsView({playlists,loaded,enqueue,refresh,favorite,initialView}:{initialView?:string;playlists:Playlist[];loaded:boolean;enqueue:(action:string,payload?:any)=>Promise<Job>;refresh:()=>Promise<void>;favorite:(p:Playlist)=>void}){
 const [query,setQuery]=useState<string>(()=>typeof savedView(initialView).query==='string'?savedView(initialView).query:''),[filters,setFilters]=useState<string[]>(()=>Array.isArray(savedView(initialView).filters)?savedView(initialView).filters.filter((f:string)=>filterChoices.includes(f)):[]),[sort,setSort]=useState(()=>savedView(initialView).sort==='last_synced'?'last_synced':'name'),[error,setError]=useState(''),[remove,setRemove]=useState<Playlist[]>([]),[removing,setRemoving]=useState(false)
 const [selected,setSelected]=useState<string[]>([]),[deletePlex,setDeletePlex]=useState(false)
 const [view,setView]=useState(()=>{try{return localStorage.getItem('playlist-bridge-view')==='compact'?'compact':'expanded'}catch{return 'expanded'}})
 const predicates=playlistPredicates
 const rows=playlists.filter(p=>filters.every(f=>predicates[f](p))&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):Date.parse(b.last_synced||'')-Date.parse(a.last_synced||'')||Number(!!b.last_synced)-Number(!!a.last_synced))
 useEffect(()=>{setSelected(current=>current.filter(key=>rows.some(p=>p.key===key)))},[query,filters,playlists])
 useEffect(()=>{try{localStorage.setItem('bridge-playlist-filters',JSON.stringify({query,filters,sort}))}catch{}},[query,filters,sort])
 useEffect(()=>{if(initialView)history.replaceState(null,'','#playlists')},[])
 const [bulkBusy,setBulkBusy]=useState(false)
 async function changeAutoSync(enabled:boolean){setBulkBusy(true);setError('');try{await api.autoSync(selected,enabled);await refresh()}catch(e:any){setError(e.message)}finally{setBulkBusy(false)}}
 const actionKeys=selected.length?selected:rows.map(p=>p.key)
 function askRemove(items:Playlist[]){setDeletePlex(false);setRemove(items)}
 async function run(fn:()=>Promise<any>){try{setError('');await fn();await refresh()}catch(e:any){setError(e.message)}}
 function toggleView(){const next=view==='compact'?'expanded':'compact';setView(next);try{localStorage.setItem('playlist-bridge-view',next)}catch{}}
 function clear(){setFilters([]);setQuery('')}
 return <section className="panel playlist-list"><div className="list-controls"><h2>Your playlists</h2><div className="actions toolbar-icons"><FilterMenu choices={Object.keys(predicates)} value={filters} onChange={setFilters}/><SortMenu choices={{name:'Name A–Z',last_synced:'Last synced'}} value={sort} onChange={setSort}/><button className="icon-button" aria-label="Refresh playlist list" title="Refresh" onClick={()=>{void refresh().catch(e=>setError(e.message))}}><Icon name="refresh"/></button><button className="icon-button" title={`Switch to ${view==='compact'?'expanded':'compact'}`} aria-label={`Switch to ${view==='compact'?'expanded':'compact'} view`} onClick={toggleView}><Icon name={view}/></button><button className="primary" disabled={!loaded||!rows.length} onClick={()=>run(()=>enqueue('sync',{scope:'selected',playlist_keys:actionKeys}))}>Sync / Refresh{rows.length?` (${actionKeys.length}${selected.length?' selected':''})`:''}</button></div></div>
 <div className="toolbar list-secondary"><input aria-label="Filter playlists by name" placeholder="Filter by playlist name" value={query} onChange={e=>setQuery(e.target.value)}/></div><FilterChips value={filters} onChange={setFilters}/>
 {loaded&&<p className="muted list-count">{rows.length} of {playlists.length} playlists{filters.length?' · all selected filters apply':''}</p>}{error&&<p className="error" role="alert">{error}</p>}
 {loaded&&!!rows.length&&<div className="selection-bar"><label><input type="checkbox" aria-label="Select all visible playlists" checked={rows.length>0&&selected.length===rows.length} onChange={e=>setSelected(e.target.checked?rows.map(p=>p.key):[])}/> Select visible</label>{!!selected.length&&<><span>{selected.length} selected</span><details className="bulk-auto"><summary><Icon name="autosync"/> Auto Sync</summary><div className="row-menu"><small>Apply to {selected.length} selected playlists</small><button disabled={bulkBusy} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');void changeAutoSync(true)}}>Turn Auto Sync On</button><button disabled={bulkBusy} onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');void changeAutoSync(false)}}>Turn Auto Sync Off</button></div></details><button className="small-button danger-action" onClick={()=>askRemove(rows.filter(p=>selected.includes(p.key)))}>Remove selected</button><button className="small-button" onClick={()=>setSelected([])}>Clear selection</button></>}</div>}
 {rows.map(p=><article className={`playlist-item ${view}`} key={p.key}><div className="playlist-main"><input type="checkbox" aria-label={`Select ${p.name}`} checked={selected.includes(p.key)} onChange={e=>setSelected(e.target.checked?[...selected,p.key]:selected.filter(k=>k!==p.key))}/><button className={`star-button ${p.favorite?'favorite':''}`} aria-label={p.favorite?`Remove ${p.name} from favorites`:`Favorite ${p.name}`} onClick={()=>favorite(p)}>{p.favorite?'★':'☆'}</button><div className="playlist-identity"><a className="playlist-name" href={link(p.key)}>{p.name}</a><p className="muted">{p.source==='spotify'?'Spotify':'Apple Music'} · {p.health?.source_tracks??p.saved_matches} tracks · <RelativeTime value={p.last_synced} prefix="Synced"/>{!p.auto_sync?' · Auto Sync off':''}</p></div><span className={`auto-sync-indicator ${p.auto_sync?'on':'off'}`} title={`Auto Sync ${p.auto_sync?'on':'off'}`} aria-label={`Auto Sync ${p.auto_sync?'on':'off'}`} role="img" tabIndex={0}><Icon name="autosync"/></span><HealthIndicator playlist={p}/><button className="small-button" onClick={()=>run(()=>enqueue('sync',{scope:'selected',playlist_keys:[p.key]}))}>Sync / Refresh</button><details className="playlist-menu"><summary aria-label={`More actions for ${p.name}`} title="More actions">⋯</summary><div className="row-menu"><button onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');void run(()=>api.updatePlaylist(p.key,{auto_sync:!p.auto_sync}))}}>Turn Auto Sync {p.auto_sync?'off':'on'}</button><button className="danger-action" onClick={e=>{e.currentTarget.closest('details')?.removeAttribute('open');askRemove([p])}}>Remove Playlist</button></div></details></div>
 {view==='expanded'&&<div className="playlist-expanded"><p className="muted">{p.saved_matches} saved matches · {p.match_counts?.automatic||0} Auto · {p.match_counts?.manual||0} Manual · {p.match_counts?.legacy||0} Saved · {p.unresolved} missing · {p.lost} LOST</p><HealthCard playlist={p}/></div>}</article>)}
 {!loaded?<p role="status">Loading playlists…</p>:!rows.length&&<div className="empty-state"><h3>{playlists.length?'No playlists match your filters':'No playlists yet'}</h3>{playlists.length?<button onClick={clear}>Clear Filters</button>:<a className="button-link" href="#dashboard/add">Add Playlist</a>}</div>}
 {!!remove.length&&<Modal onClose={()=>setRemove([])} busy={removing}><div className="modal" role="dialog" aria-modal="true" aria-label="Remove playlists"><h2>Remove {remove.length} playlist{remove.length===1?'':'s'}?</h2><ul>{remove.map(p=><li key={p.key}>{p.name}</li>)}</ul><label className="playlist-choice"><input type="radio" name="remove-mode" checked={!deletePlex} onChange={()=>setDeletePlex(false)}/> Remove from Bridge only — leave Plex playlists untouched</label><label className="playlist-choice"><input type="radio" name="remove-mode" checked={deletePlex} onChange={()=>setDeletePlex(true)}/> Also delete these playlists from Plex</label><p>{deletePlex?'The selected Plex playlists will be deleted. Music files in your library are not deleted.':'Plex playlists will remain unchanged.'} Historical job output is retained.</p>{error&&<p className="error">{error}</p>}<div className="actions"><button disabled={removing} onClick={()=>setRemove([])}>Cancel</button><button disabled={removing} className={deletePlex?'danger-action':''} onClick={async()=>{setRemoving(true);try{await enqueue('remove',{playlist_keys:remove.map(p=>p.key),delete_plex:deletePlex});setRemove([]);setSelected([])}catch(e:any){setError(e.message)}finally{setRemoving(false)}}}>{deletePlex?'Delete from Bridge and Plex':'Remove from Bridge only'}</button></div></div></Modal>}

 </section>
}
