import {useEffect,useState} from 'react'
import ErrorNotice from './ErrorNotice'
export default function PlaylistSchedule({playlistKey}:{playlistKey:string}){
 const [value,setValue]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState('')
 const path='/api/playlist-schedule/'+encodeURIComponent(playlistKey)
 useEffect(()=>{let alive=true;fetch(path).then(async r=>{if(!r.ok)throw new Error('Could not load schedule');return r.json()}).then(v=>{if(alive)setValue(v)}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[path])
 async function save(){setBusy(true);setError('');try{const r=await fetch(path,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)});const data=await r.json();if(!r.ok)throw new Error(typeof data.detail==='string'?data.detail:'Choose valid schedule options');setValue(data);setSaved('Sync mode saved.');window.dispatchEvent(new Event('jobs-refresh'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <details className="playlist-schedule"><summary>Sync mode{value?.mode==='custom'?' · Custom':value?.mode==='disabled'?' · Manual only':''}</summary>{error&&<ErrorNotice error={error}/ >}{value&&<><label>Schedule<select value={value.mode} disabled={busy} onChange={e=>{setValue({...value,mode:e.target.value});setSaved('')}}><option value="inherit">Server schedule</option><option value="custom">Custom schedule</option><option value="disabled">Manual only</option></select></label>{value.mode==='custom'&&<><div className="schedule-days">{['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'].map((day,i)=><label key={day}><input type="checkbox" checked={value.days.includes(i)} onChange={e=>setValue({...value,days:e.target.checked?[...value.days,i]:value.days.filter((d:number)=>d!==i)})}/>{day}</label>)}</div><label>Time<input type="time" value={`${String(value.hour).padStart(2,'0')}:${String(value.minute).padStart(2,'0')}`} onChange={e=>{const [hour,minute]=e.target.value.split(':').map(Number);setValue({...value,hour,minute})}}/></label></>}<p>Timezone: {value.timezone}. {value.next_run?`Next run: ${new Date(value.next_run).toLocaleString()}`:value.mode==='inherit'?'Follows the global Sync Playlists task.':'No scheduled run.'}</p><p className="muted">Custom schedules run independently, even when the server task is disabled. Manual syncs do not shift the schedule. A run is skipped if a sync is already queued or running.</p><button disabled={busy||(value.mode==='custom'&&!value.days.length)} onClick={save}>Save Schedule</button>{saved&&<p role="status">{saved}</p>}</>}</details>
}
