import {AddLidarrAlbum} from './Lidarr'
import ErrorNotice from './ErrorNotice'
import {usePageState} from './Navigation'
import { useEffect, useState } from 'react'
import { trackLink } from './Controls'
import { api } from './api'
export default function SearchPage(){
 const [albumQuery,setAlbumQuery]=useState(''),[albumSearch,setAlbumSearch]=useState<string|null>(null)
 const [query,setQuery]=usePageState('search-query',''),[result,setResult]=useState<any>(null),[error,setError]=useState(''),[loading,setLoading]=useState(false)
 useEffect(()=>{let alive=true;setError('');setResult(null);setLoading(!!query.trim());if(!query.trim())return;const timer=setTimeout(async()=>{try{const rows=await api.search(query.trim());if(alive)setResult(rows)}catch(e:any){if(alive)setError(e.message)}finally{if(alive)setLoading(false)}},300);return()=>{alive=false;clearTimeout(timer)}},[query])
 return <><section className="panel"><h2>Find albums to request</h2><form className="add" onSubmit={e=>{e.preventDefault();if(albumQuery.trim())setAlbumSearch(albumQuery.trim())}}><input aria-label="Search albums" placeholder="Artist - Album" value={albumQuery} onChange={e=>setAlbumQuery(e.target.value)}/><button disabled={!albumQuery.trim()}>Search Albums</button></form>{albumSearch!==null&&<AddLidarrAlbum track={{title:'',artist:'',album:''}} searchQuery={albumSearch} onClose={()=>setAlbumSearch(null)}/>}</section><section className="panel search-page"><label htmlFor="global-search">Search across Playlist Bridge</label><input id="global-search" autoFocus type="search" placeholder="Playlist, track, artist or album" value={query} onChange={e=>setQuery(e.target.value)}/><p className="muted">Search your saved playlists and tracks. Sync / Refresh updates the saved track lists.</p>{error&&<ErrorNotice error={error}/>}{loading&&<p role="status">Searching…</p>}{!query.trim()&&<p>Enter a name to find playlists or tracks across your collection.</p>}{result&&<><h2>Playlists ({result.playlists.length})</h2>{result.playlists.map((p:any)=><p key={p.key}><a href={`#playlist/${encodeURIComponent(p.key)}`}>{p.name}</a></p>)}<h2>Tracks ({result.track_count})</h2>{result.track_count>200&&<p className="muted">Showing the first 200 tracks. Refine your search to narrow the results.</p>}{result.tracks.map((t:any,i:number)=><article className="search-result" key={i}><a className="track-title" href={trackLink(t)}>{t.title}</a><p>{t.artist}{t.album?` · ${t.album}`:''} · <a href={`#playlist/${encodeURIComponent(t.playlist_key)}`}>{t.playlist_name}</a></p></article>)}<h2>Plex inventory</h2><p className="muted">Last scan: {result.inventory_checked_at?.plex?new Date(result.inventory_checked_at.plex*1000).toLocaleString():'Not scanned'}</p>{result.plex_tracks?.map((t:any)=><p key={t.plex_id}>{t.title} — {t.artist} · {t.album} · Available at last scan</p>)}<h2>Managed album inventory</h2><p className="muted">Last scan: {result.inventory_checked_at?.lidarr?new Date(result.inventory_checked_at.lidarr*1000).toLocaleString():'Not scanned'}</p>{result.lidarr_albums?.map((a:any)=><p key={a.id}><button onClick={()=>setAlbumSearch(`${a.artist} - ${a.title}`)}>{a.artist} — {a.title}</button> · Managed at last scan</p>)}{!result.playlists.length&&!result.track_count&&!result.plex_tracks?.length&&!result.lidarr_albums?.length&&<div className="empty-state"><p>No results for “{query}”. Try another name or artist.</p><button onClick={()=>setQuery('')}>Clear Search</button></div>}</>}</section></>
}
