import { useEffect, useState } from 'react'
import { api, Job } from './api'
import { stamp } from './HealthCard'
import { Icon } from './Controls'
import Modal from './Modal'

export function About({jobs}:{jobs:Job[]}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const revision=jobs.filter(j=>j.action==='check_updates').map(j=>`${j.id}:${j.status}`).join('|')
 useEffect(()=>{api.updates().then(setData).catch(e=>setError(e.message))},[revision])
 const active=jobs.some(j=>j.action==='check_updates'&&['queued','running','cancelling'].includes(j.status))
 return <section className="panel about-page"><h2>Playlist Bridge</h2><p>Playlist Bridge 2.0</p><div className="about-update"><Icon name="refresh"/><div><h3>{data?.available?'An update is available':data?.error?'Update check unavailable':data?.checked_at?'You’re up to date':'Update check pending'}</h3>{data?.available&&<p>Available version: {data.latest_version}</p>}<p className="muted">Last checked: {data?.checked_at?stamp(data.checked_at):'Not yet checked'}</p>{data?.error&&<p className="error">{data.error}</p>}</div></div><button disabled={busy||active} onClick={async()=>{setBusy(true);try{await api.checkUpdates();setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>{active?'Check queued / running…':'Check for Updates'}</button>{error&&<p className="error">{error}</p>}<p className="muted">Checks the {data?.channel||'main'} channel every six hours, aligned to midnight. Updates are installed through Docker. Your data remains in the existing data directory.</p><p><a href="https://github.com/rstuke82/playlist-bridge/releases" target="_blank" rel="noreferrer">Release notes ↗</a> · <a href="#settings/tasks">View tasks</a></p></section>
}

export function Backups({jobs}:{jobs:Job[]}){
 const [data,setData]=useState<any>(null),[task,setTask]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[restore,setRestore]=useState<any>(null)
 const revision=jobs.filter(j=>['backup','restore_backup'].includes(j.action)).map(j=>`${j.id}:${j.status}`).join('|')
 async function load(){try{const [d,t]=await Promise.all([api.backups(),api.tasks()]);setData(d);setTask(t.tasks.find((v:any)=>v.action==='backup'));setError('')}catch(e:any){setError(e.message)}}
 useEffect(()=>{void load()},[revision])
 async function run(fn:()=>Promise<any>){setBusy(true);try{await fn();await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const active=jobs.some(j=>['backup','restore_backup'].includes(j.action)&&['queued','running','cancelling'].includes(j.status))
 return <section className="panel"><div className="panel-head"><h2>Backups</h2><button className="primary" disabled={busy||active} onClick={()=>run(()=>api.enqueue('backup'))}>{active?'Backup / restore in progress…':'Back Up Now'}</button></div><p className="muted">Backs up registered playlists, matches, settings, schedules and job history. Plex music and playlists are not included. Browser appearance and filter preferences stay in your browser.</p><div className="backup-summary"><div><small>Last successful backup</small><strong>{data?.backups[0]?stamp(data.backups[0].created_at):'No backups yet'}</strong></div><div><small>Next scheduled backup</small><strong>{task?.next_run?stamp(task.next_run):task?'Disabled':'Loading…'}</strong><a href="#settings/tasks">Manage schedule</a></div></div><label className="retention-choice">Keep scheduled backups <select value={data?.retention||14} disabled={busy||!data} onChange={e=>run(()=>api.backupSettings(Number(e.target.value)))}>{[7,14,30].map(n=><option key={n} value={n}>{n} backups</option>)}</select></label><p className="muted">Daily at midnight by default. Also keeps the latest five manual backups and five pre-restore backups. Backups contain connection credentials; download them to a private location.</p>{error&&<p className="error">{error}</p>}{!data&&!error&&<p>Loading backups…</p>}{data?.backups.map((b:any)=><article className="backup-row" key={b.name}><div><strong>{stamp(b.created_at)}</strong><small>{b.kind==='before-restore'?'Safety backup':b.kind==='daily'?'Scheduled':'Manual'} · {b.version} · {(b.bytes/1024/1024).toFixed(2)} MB</small></div><div className="actions"><a className="button-link small-button" href={`/api/backups/${encodeURIComponent(b.name)}/download`} download><Icon name="download"/> Download</a><button disabled={busy||active} onClick={()=>setRestore(b)}>Restore</button></div></article>)}{data&&!data.backups.length&&<p>No backups yet. The first daily backup will run at midnight, or choose Back Up Now.</p>}
 {restore&&<Modal onClose={()=>setRestore(null)} busy={busy}><div className="modal" role="dialog" aria-modal="true" aria-label="Restore backup"><h2>Restore this backup?</h2><p>{stamp(restore.created_at)} · {restore.version}</p><p>This replaces Playlist Bridge settings, registrations, mappings, schedules and history with this snapshot. Plex playlists remain untouched. Work queued before the restore is cancelled.</p><p>A safety backup of the current app data will be created first.</p><div className="actions"><button disabled={busy} onClick={()=>setRestore(null)}>Cancel</button><button disabled={busy} className="danger-action" onClick={()=>run(async()=>{await api.restoreBackup(restore.name);setRestore(null)})}>Restore Backup</button></div>{error&&<p className="error">{error}</p>}</div></Modal>}
 </section>
}

export function Ignored(){
 const [rows,setRows]=useState<any[]|null>(null),[error,setError]=useState(''),[query,setQuery]=useState(''),[scope,setScope]=useState('all'),[selected,setSelected]=useState<string[]>([]),[busy,setBusy]=useState(false)
 const id=(r:any)=>JSON.stringify([r.playlist_key,r.ignore_key])
 async function load(){setRows(await api.ignored())}
 useEffect(()=>{load().catch(e=>setError(e.message))},[])
 const filtered=(rows||[]).filter(r=>(scope==='all'||r.playlist_key===scope)&&`${r.title} ${r.artist}`.toLowerCase().includes(query.toLowerCase()))
 async function restore(items:any[]){setBusy(true);setError('');try{for(const r of items)await api.restoreIgnore({playlist_key:r.playlist_key,ignore_key:r.ignore_key});setSelected([])}catch(e:any){setError(e.message)}finally{await load().catch(e=>setError(e.message));setBusy(false)}}
 return <section className="panel ignored-page"><h2>Ignored Tracks</h2><p className="muted">Restoring a rule lets matching consider the track on its next sync.</p><div className="toolbar"><input aria-label="Filter ignored tracks" placeholder="Filter tracks or artists" value={query} onChange={e=>{setQuery(e.target.value);setSelected([])}}/><select aria-label="Filter ignored tracks by playlist" value={scope} onChange={e=>{setScope(e.target.value);setSelected([])}}><option value="all">All playlists</option>{Array.from(new Set((rows||[]).map(r=>r.playlist_key))).map(k=><option key={k} value={k}>{k==='__global__'?'Universal rules':k}</option>)}</select></div><div className="selection-bar"><button disabled={busy||!filtered.length} onClick={()=>setSelected(filtered.map(id))}>Select visible</button><button disabled={busy||!selected.length} onClick={()=>restore(filtered.filter(r=>selected.includes(id(r))))}>Restore selected ({selected.length})</button><button onClick={()=>setSelected([])}>Clear selection</button></div>{error&&<p className="error">{error}</p>}{filtered.map(r=><article className="ignored-item" key={id(r)}><input type="checkbox" aria-label={`Select ${r.title}`} checked={selected.includes(id(r))} onChange={e=>setSelected(e.target.checked?[...selected,id(r)]:selected.filter(k=>k!==id(r)))}/><div><strong>{r.title}</strong><span>{r.artist}</span><small>{r.playlist_key==='__global__'?'Universal rule':r.playlist_key}</small></div><button disabled={busy} onClick={()=>restore([r])}>Restore</button></article>)}{rows===null&&!error?<p>Loading ignored tracks…</p>:rows&&!filtered.length&&<p>No ignored tracks match this view.</p>}</section>
}

export function Matching(){
 const [aliases,setAliases]=useState<Record<string,string[]>>({}),[loaded,setLoaded]=useState(false),[canonical,setCanonical]=useState(''),[values,setValues]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 useEffect(()=>{api.matching().then(d=>{setAliases(d.aliases);setLoaded(true)}).catch(e=>setError(e.message))},[])
 async function save(){setBusy(true);try{setAliases((await api.saveAlias(canonical,values.split('\n'))).aliases);setCanonical('');setValues('');setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <section className="panel"><h2>Matching</h2><p className="muted">Automatic matching uses the existing matching rules and thresholds. Artist aliases let the matcher recognize alternate artist names.</p><h3>Artist aliases</h3>{error&&<p className="error">{error}</p>}{!loaded&&!error&&<p>Loading aliases…</p>}{Object.entries(aliases).map(([name,list])=><div className="alias-row" key={name}><div><strong>{name}</strong><p>{Array.isArray(list)?list.join(', '):String(list)}</p></div><button onClick={()=>{setCanonical(name);setValues(Array.isArray(list)?list.join('\n'):String(list))}}>Edit</button></div>)}<div className="form-grid"><label>Canonical artist<input value={canonical} onChange={e=>setCanonical(e.target.value)}/></label><label>Aliases, one per line<textarea rows={4} value={values} onChange={e=>setValues(e.target.value)}/></label></div><p className="muted">Save an existing artist with an empty alias list to remove its alias group.</p>{(canonical||values)&&<div className="settings-save"><button disabled={busy||!canonical.trim()} className="primary" onClick={save}>Save Changes</button><button disabled={busy} onClick={()=>{setCanonical('');setValues('')}}>Cancel</button></div>}</section>
}
