import {useEffect,useRef,useState} from 'react'
import {request} from './api'
import {useAccount} from './Auth'
export default function SharedPlaylists(){
 const user=useAccount(),[rows,setRows]=useState<any[]>([]),[url,setUrl]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false)
 const generation=useRef(0),edited=useRef(false)
 const load=()=>request<any[]>('/api/shared-playlists').then(setRows).catch(e=>setMessage(e.message))
 useEffect(()=>{if(user?.admin)void load()},[])
 async function lookup(){if(!url)return;setMessage('Reading source name…');const g=++generation.current;setLoading(true);try{const data=await request<any>('/api/shared-playlists/metadata',{method:'POST',body:JSON.stringify({url})});if(g===generation.current){if(!edited.current)setName(data.name);setMessage('')}}catch(e:any){if(g===generation.current)setMessage(e.message)}finally{if(g===generation.current)setLoading(false)}}
 if(!user?.admin)return null
 return <details className="panel"><summary>Shared playlist sources</summary><p>Manage source playlists and add a copy to your Plex account.</p>{rows.map(r=><div className="shared-source-row" key={r.id}><span>{r.name}</span><button onClick={async()=>{try{const job=await request<any>(`/api/shared-playlists/${r.id}/subscribe`,{method:'POST'});setMessage('Playlist queued.');window.dispatchEvent(new CustomEvent('bridge-notice',{detail:{message:'Playlist queued.',job_id:job.id}}))}catch(e:any){setMessage(e.message)}}}>Add my copy</button><button onClick={async()=>{try{await request('/api/shared-playlists/'+r.id,{method:'DELETE'});await load()}catch(e:any){setMessage(e.message)}}}>Unpublish source</button></div>)}<form className="shared-source-form" onSubmit={async e=>{e.preventDefault();try{await request('/api/shared-playlists',{method:'POST',body:JSON.stringify({url,name})});setUrl('');setName('');edited.current=false;await load()}catch(e:any){setMessage(e.message)}}}><label>Playlist URL<input required type="url" value={url} onBlur={lookup} onChange={e=>{generation.current++;setLoading(false);setUrl(e.target.value);if(!edited.current)setName('');setMessage('')}}/></label><label>Name<input required value={name} placeholder={loading?'Reading source name…':'Source playlist name'} onChange={e=>{edited.current=true;setName(e.target.value)}}/></label><button disabled={loading||!name.trim()}>Publish shared source</button></form><p role="status">{message}</p></details>
}
