import {useEffect,useRef,useState} from 'react'
import {request} from './api'
import {useAccount} from './Auth'
import Modal from './Modal'
export default function SharedPlaylists(){
 const user=useAccount(),[rows,setRows]=useState<any[]>([]),[url,setUrl]=useState(''),[name,setName]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false),[preview,setPreview]=useState<any>(null),[busy,setBusy]=useState(false)
 const generation=useRef(0),edited=useRef(false)
 const load=()=>request<any[]>('/api/shared-playlists').then(setRows).catch(e=>setMessage(e.message))
 useEffect(()=>{void load()},[])
 async function lookup(){if(!url)return;const g=++generation.current;setLoading(true);try{const data=await request<any>('/api/shared-playlists/metadata',{method:'POST',body:JSON.stringify({url})});if(g===generation.current&&!edited.current)setName(data.name)}catch(e:any){setMessage(e.message)}finally{if(g===generation.current)setLoading(false)}}
 async function add(r:any){setBusy(true);try{const job=await request<any>(`/api/shared-playlists/${r.id}/subscribe`,{method:'POST'});setRows(v=>v.map(x=>x.id===r.id?{...x,subscribed:true}:x));setPreview(null);window.dispatchEvent(new CustomEvent('bridge-notice',{detail:{message:'Playlist queued.',job_id:job.id}}))}catch(e:any){setMessage(e.message)}finally{setBusy(false)}}
 const visible=rows.filter(r=>!r.subscribed)
 return <>{!!visible.length&&<details className="panel"><summary>Shared playlists</summary><p>Preview a shared source or add your own Plex copy.</p>{visible.map(r=><div className="shared-source-row" key={r.id}><button className="text-button" onClick={async()=>{setPreview({...r,loading:true});try{const p=await request<any>(`/api/shared-playlists/${r.id}/preview`);setPreview({...r,...p})}catch(e:any){setPreview({...r,error:e.message})}}}>{r.name}</button><button disabled={busy||user?.can_playlists===false&&!user?.admin} onClick={()=>add(r)}>Add My Copy</button></div>)}</details>}{user?.admin&&<details className="panel"><summary>Manage shared sources</summary>{rows.map(r=><div className="shared-source-row" key={r.id}><span>{r.name}</span><button onClick={async()=>{try{await request('/api/shared-playlists/'+r.id,{method:'DELETE'});await load()}catch(e:any){setMessage(e.message)}}}>Unpublish</button></div>)}<form className="shared-source-form" onSubmit={async e=>{e.preventDefault();try{await request('/api/shared-playlists',{method:'POST',body:JSON.stringify({url,name,custom_name:edited.current})});setUrl('');setName('');edited.current=false;await load()}catch(e:any){setMessage(e.message)}}}><label>Playlist URL<input required type="url" value={url} onBlur={lookup} onChange={e=>{generation.current++;setUrl(e.target.value);edited.current=false;setName('')}}/></label><label>Name<input required value={name} placeholder="Source playlist name" onChange={e=>{edited.current=true;setName(e.target.value)}}/></label><button disabled={loading||!name.trim()}>Publish shared source</button></form></details>}{message&&<p role="status">{message}</p>}{preview&&<Modal onClose={()=>setPreview(null)}><section className="modal" role="dialog" aria-modal="true" aria-label="Shared playlist preview"><div className="modal-header"><h2>{preview.name}</h2><button onClick={()=>setPreview(null)}>Close</button></div><div className="modal-body">{preview.loading&&<p>Loading source tracks…</p>}{preview.error&&<p role="alert">{preview.error}</p>}{preview.tracks?.map((t:any,i:number)=><div className="missing-row" key={i}><span>{i+1}. {t.title}<small>{t.artist} · {t.album||'Unknown album'}</small></span><span>{t.availability}</span></div>)}</div><div className="modal-footer"><button disabled={busy||preview.loading||user?.can_playlists===false&&!user?.admin} onClick={()=>add(preview)}>Add My Copy</button></div></section></Modal>}</>
}
