import {useState} from 'react'
import {request} from './api'
import Modal from './Modal'
import ErrorNotice from './ErrorNotice'
export default function TextPlaylist({sourceId}:{sourceId?:string}){
 const [open,setOpen]=useState(false),[name,setName]=useState(''),[text,setText]=useState(''),[format,setFormat]=useState('artist-title'),[rows,setRows]=useState<any[]>([]),[revision,setRevision]=useState(0),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function start(){setError('');setOpen(true);if(sourceId){setBusy(true);try{const d=await request<any>('/api/playlists/text/'+sourceId);setName(d.name);setRows(d.tracks);setRevision(d.revision)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}
 async function parse(){setBusy(true);setError('');try{const d=await request<any>('/api/playlists/text/parse',{method:'POST',body:JSON.stringify({text,format})});setRows(d.rows)}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{const j=await request<any>('/api/playlists/text',{method:'POST',body:JSON.stringify({name,tracks:rows.map(({title,artist,album})=>({title,artist,album:album||''})),source_id:sourceId||null,revision})});setOpen(false);if(!sourceId){setName('');setText('');setRows([])}window.dispatchEvent(new CustomEvent('bridge-notice',{detail:{message:'Text playlist saved to the queue. Matching and sync will run in Activity.',job_id:j.id}}));window.dispatchEvent(new Event('jobs-refresh'))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <><button onClick={start}>{sourceId?'Edit Track List':'Create from Text'}</button>{open&&<Modal onClose={()=>setOpen(false)} busy={busy}><section className="modal match-dialog" role="dialog" aria-modal="true" aria-label="Create playlist from text"><div className="modal-header"><h2>{sourceId?'Edit custom playlist':'Create from Text'}</h2><button disabled={busy} onClick={()=>setOpen(false)}>Close</button></div><div className="modal-body"><label>Playlist name<input value={name} maxLength={200} onChange={e=>setName(e.target.value)}/></label><p>Paste a list from an AI, a document, or your own notes. Review the rows before saving. Duplicates and order are kept.</p><label>Line format<select value={format} onChange={e=>setFormat(e.target.value)}><option value="artist-title">Artist — Song — Album (optional)</option><option value="title-artist">Song — Artist — Album (optional)</option></select></label><textarea rows={7} style={{width:'100%'}} value={text} onChange={e=>setText(e.target.value)} placeholder={'1. CAKE — The Distance — Fashion Nugget\n2. Weezer — Buddy Holly'}/><button disabled={busy||!text.trim()} onClick={parse}>Parse / Replace Rows</button>{error&&<ErrorNotice error={error}/ >}{rows.map((r,i)=><div className="text-track-row" key={i}><span>{i+1}</span>{['artist','title','album'].map(k=><input key={k} aria-label={`${k} for row ${i+1}`} placeholder={k} value={r[k]||''} onChange={e=>setRows(v=>v.map((x,j)=>j===i?{...x,[k]:e.target.value}:x))}/>)}<button onClick={()=>setRows(v=>v.filter((_,j)=>j!==i))}>Remove</button>{(!r.artist.trim()||!r.title.trim())&&<small role="status">Needs review: enter an artist and song title.</small>}</div>)}<button onClick={()=>setRows(v=>[...v,{artist:'',title:'',album:''}])}>Add Row</button><p>Saving updates this source and queues a sync. Missing songs remain available for review and album requests.</p></div><div className="modal-footer"><button disabled={busy||!name.trim()||!rows.length||rows.some(r=>!r.artist.trim()||!r.title.trim())} onClick={save}>{busy?'Working…':'Save & Sync'}</button></div></section></Modal>}</>
}
