import { useCallback, useEffect, useState } from 'react'
import { api, Job, activeJob } from './api'
import { FilterMenu, FilterChips, SortMenu, Icon } from './Controls'
export default function TrackDetails({track,jobs,enqueue}:{track:any;jobs:Job[];enqueue:(action:string,payload?:any)=>Promise<Job>}){
 const [data,setData]=useState<any>(null),[keys,setKeys]=useState<string[]>([]),[query,setQuery]=useState(''),[filters,setFilters]=useState<string[]>([]),[sort,setSort]=useState('name'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>(null),[manual,setManual]=useState(false),[search,setSearch]=useState(''),[candidates,setCandidates]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[jobId,setJobId]=useState('')
 const identity=JSON.stringify(track)
 const load=useCallback(async()=>{setBusy(true);try{const value=await api.trackDetails(JSON.parse(identity));setData(value);setKeys(old=>old.filter(k=>value.memberships.some((m:any)=>m.key===k)));setPreview(null);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}},[identity])
 useEffect(()=>{void load()},[load])
 const job=jobs.find(j=>j.id===jobId)
 useEffect(()=>{if(job&&!activeJob(job)){void load();setJobId('')}},[job?.status,load])
 function selection(next:string[]){setKeys(next);setPreview(null)}
 async function makePreview(mode:string){setBusy(true);setError('');try{setPreview(await api.trackPreview({...track,mode,playlist_keys:keys,plex_id:mode==='manual'?selected?.plex_id:undefined}))}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function find(){setBusy(true);try{setCandidates(await api.candidates({...track,query:search}));setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 const rows=(data?.memberships||[]).filter((m:any)=>m.name.toLowerCase().includes(query.toLowerCase())&&filters.every(f=>m.statuses[f.toLowerCase()]>0)).sort((a:any,b:any)=>sort==='occurrences'?b.occurrences-a.occurrences:a.name.localeCompare(b.name))
 const count=data?.memberships.filter((m:any)=>keys.includes(m.key)).reduce((n:number,m:any)=>n+m.occurrences,0)||0
 return <><a href="#search">← Search</a><section className="panel track-heading"><div><h2>{track.title}</h2><p>{track.artist}{track.album?` · ${track.album}`:''}</p>{data&&<p className="muted">{data.occurrences} saved occurrences in {data.memberships.length} playlists</p>}</div><div className="actions"><button disabled={busy||!keys.length} onClick={()=>{setManual(true);setPreview(null)}}>Choose Manual Match</button><button className="primary" disabled={busy||!keys.length} onClick={()=>{setManual(false);void makePreview('automatic')}}>Retry Automatic Matching</button></div></section>
 {error&&<p className="error" role="alert">{error}</p>}{busy&&<p role="status">Loading track data / preparing match preview…</p>}
 <div className="track-layout"><section className="panel"><div className="panel-head"><h2>Playlists containing this track</h2><div className="actions"><FilterMenu choices={['Automatic','Manual','Legacy','Unresolved','LOST','Ignored']} value={filters} onChange={setFilters}/><SortMenu choices={{name:'Playlist name',occurrences:'Most occurrences'}} value={sort} onChange={setSort}/><button className="icon-button" title="Refresh track details" aria-label="Refresh track details" disabled={busy} onClick={load}><Icon name="refresh"/></button></div></div><input className="track-search" placeholder="Filter playlists" value={query} onChange={e=>setQuery(e.target.value)}/><FilterChips value={filters} onChange={setFilters}/><div className="selection-bar"><span>{keys.length} playlists selected · {count} occurrences</span><button className="small-button" onClick={()=>selection(rows.map((r:any)=>r.key))}>Select visible</button><button className="small-button" onClick={()=>selection(data?.memberships.map((m:any)=>m.key)||[])}>Select all</button><button className="small-button" onClick={()=>selection([])}>Clear selection</button></div><div className="table-scroll"><table className="track-table"><thead><tr><th>Select</th><th>Playlist</th><th>Occurrences</th><th>Match type / Current Plex match</th></tr></thead><tbody>{rows.map((m:any)=><tr key={m.key}><td><input aria-label={`Select ${m.name}`} type="checkbox" checked={keys.includes(m.key)} onChange={e=>selection(e.target.checked?[...keys,m.key]:keys.filter(k=>k!==m.key))}/></td><td><a href={`#playlist/${encodeURIComponent(m.key)}`}>{m.name}</a></td><td>{m.occurrences}{!m.count_exact?' (known minimum)':''}</td><td>{Array.from(new Map(m.tracks.map((t:any)=>[`${t.status}:${t.plex_id}`,t])).values()).map((t:any,i)=><div key={i}><span className="pill">{t.status==='automatic'?'Auto':t.status}</span><small>{t.plex_id?`${t.match?.title||track.title} — ${t.match?.artist||'Plex ID '+t.plex_id}`:'No match'}</small></div>)}</td></tr>)}</tbody></table></div>{data&&!rows.length&&<div className="empty-state"><p>No known playlist occurrences match this view.</p><button onClick={()=>{setQuery('');setFilters([])}}>Clear Filters</button></div>}<p className="muted">Membership uses saved source lists and health results. Refresh a playlist to discover source changes. Matching uses the existing track-identity rules.</p>{data?.unknown_playlists.length>0&&<details><summary>{data.unknown_playlists.length} playlists need a source refresh for exact membership counts</summary>{data.unknown_playlists.map((name:string)=><p key={name}>{name}</p>)}</details>}</section>
 <section className="panel preview-panel"><h2>{preview?`${preview.mode==='automatic'?'Automatic':'Manual'} match preview`:'Review changes'}</h2>{!preview&&<p>Select playlists, then retry automatic matching or choose a manual match. Your saved matches remain unchanged until you apply a preview.</p>}{preview&&<><p>{preview.playlist_count} playlists · {preview.occurrences} occurrences will change</p>{preview.changes.map((c:any,i:number)=><div className="preview-change" key={i}><strong>{c.playlist_name}</strong><p>{c.candidate.title} — {c.candidate.artist}</p><span>{c.before} → {c.provenance==='automatic'?'Auto':'Manual'}</span></div>)}{preview.unchanged.map((c:any,i:number)=><p className="muted" key={i}>{c.playlist}: {c.reason}</p>)}<p>Only the listed playlists will sync. Duplicate occurrences and source order are retained where Plex supports them.</p><div className="actions"><button className="primary" disabled={busy||!preview.changes.length} onClick={async()=>{setBusy(true);try{const j=await enqueue('track_match',{preview_id:preview.preview_id});setJobId(j.id);setPreview(null)}catch(e:any){setError(e.message)}finally{setBusy(false)}}}>Apply {preview.mode==='automatic'?'Automatic':'Manual'} Match</button><button onClick={()=>setPreview(null)}>Cancel</button></div></>}</section></div>
 {manual&&<section className="panel"><h2>Choose a manual match</h2><form className="add" onSubmit={e=>{e.preventDefault();void find()}}><input aria-label="Search Plex library" placeholder="Search Plex library" value={search} onChange={e=>setSearch(e.target.value)}/><button disabled={busy}>Search</button></form>{candidates.map(c=><button className={`candidate ${selected?.plex_id===c.plex_id?'chosen':''}`} key={c.plex_id} onClick={()=>{setSelected(c);setPreview(null)}}>{c.title} — {c.artist} · {c.album}</button>)}<button disabled={busy||!selected||!keys.length} onClick={()=>makePreview('manual')}>Preview Manual Match for {keys.length} Playlists</button></section>}</>
}
